### ISSUE TITLE
System.ArgumentException: The provided URI scheme 'https' is invalid; expected 'http'

### ISSUE THREAD

**Issue by davitgr** [Travelport/travelport-uapi-tutorial-c-sharp#110]
When doing a ping request, after the call **Task<SystemReference.serviceResponse> rsp = client.serviceAsync(req);**, I am getting error **System.ArgumentException: The provided URI scheme 'https' is invalid; expected 'http'**. I am using Visual Studio 2017 Enterprise with .NET Core 2.0. Can you please help me resolve this issue.

Below is the code snippet:

           String payload = "this my payload; there are many like it but this one is mine";
            String someTraceId = "doesntmatter-8176";
            String originApp = "UAPI";

            PingReq req = new PingReq();
            req.Payload = payload;
            req.TraceId = someTraceId;

            SystemReference.BillingPointOfSaleInfo billSetInfo = new 
            SystemReference.BillingPointOfSaleInfo();
            billSetInfo.OriginApplication = originApp;

            req.BillingPointOfSaleInfo = billSetInfo;
            req.TargetBranch = "P108154";

            SystemPingPortTypeClient client = new 
            SystemPingPortTypeClient(SystemPingPortTypeClient.EndpointConfiguration.SystemPingPort, WsdlService.SYSTEM_ENDPOINT);

                client.ClientCredentials.UserName.UserName = Helper.RetrunUsername();
                client.ClientCredentials.UserName.Password = Helper.ReturnPassword();

                var httpHeaders = Helper.ReturnHttpHeader();
                client.Endpoint.EndpointBehaviors.Add(new HttpHeadersEndpointBehavior(httpHeaders));

                Task<SystemReference.serviceResponse> rsp = client.serviceAsync(req);

**Comment by NirandaG** [comment]
Hi davitgr,
Has the WSDL files created successfully?
Could you try the following instead of client.serviceAsync :
var httpHeaders = Helper.ReturnHttpHeader();                
                client.Endpoint.EndpointBehaviors.Add(new HttpHeadersEndpointBehavior(httpHeaders));                
  
PingRsp rsp = client.service(req);

Let us know if yo still get the same issue.
Thank you,
Niranda

**Comment by davitgr** [comment]
Hi NirandaG,

The WSDL files have been created successfully. I used the latest version files from the Travelport site.  I am unable to call client.service(req) because client does not contain a definition for service, only serviceAsync(), which is why I was using serviceAsync(). What should I do now?

**Comment by davitgr** [comment]
Hi Niranda,

Do you have any updates?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

I am working on this and will provide an update. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

Do you have any updates regarding my issue? I can't do anything without
having a solution.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

We are still working on it and will provide an update by tomorrow. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Could you please check an confirm if you are using basicHttpBinding or customBinding. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

I searched through the entire solution, the only place I found basicHttpBinding was in the methods that were automatically generated from the WSDL files. There was no customBinding.

Below is the code from appsettings.json

{
  "Username": "Universal API/HIDDEN",
  "Password": "HIDDEN",
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "HIDDEN"
  }
}

Please let me know what other infomation you need so that we can resolve this issue together.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Could you please replace the proxy reference.cs you have generated with the attached file and give it a try with the below code. Please let us know how it goes. Thanks.

[SystemReference.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/1720774/SystemReference.zip)

```xml
String payload = "this my payload; there are many like it but this one is mine";
        String someTraceId = "doesntmatter-8176";
        String originApp = "UAPI";

        PingReq req = new PingReq();
        req.Payload = payload;
        req.TraceId = someTraceId;

        SystemReference.BillingPointOfSaleInfo billSetInfo = new 
        SystemReference.BillingPointOfSaleInfo();
        billSetInfo.OriginApplication = originApp;

        req.BillingPointOfSaleInfo = billSetInfo;
        req.TargetBranch = "P108154";

        SystemPingPortTypeClient client = new 
        SystemPingPortTypeClient(SystemPingPortTypeClient.EndpointConfiguration.SystemPingPort, WsdlService.SYSTEM_ENDPOINT);

            client.ClientCredentials.UserName.UserName = Helper.RetrunUsername();
            client.ClientCredentials.UserName.Password = Helper.ReturnPassword();

            var httpHeaders = Helper.ReturnHttpHeader();
            client.Endpoint.EndpointBehaviors.Add(new HttpHeadersEndpointBehavior(httpHeaders));

           PingRsp rsp = client.service(req);
```

**Comment by davitgr** [comment]
Hi Vivek,

I tried with the files and test code you sent, but I am still getting the same error. What should I do next? Please let me know how we can resolve this issue soon.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

The code and the files I sent, it is working fine without any issues from our side. Please confirm the exact code you are using. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

Please see below:

            //
            // PING REQUEST
            //
            String payload = "this my payload; there are many like it but this one is mine";
            String someTraceId = "doesntmatter-8176";
            String originApp = "UAPI";

            //set up the request parameters into a PingReq object
            PingReq req = new PingReq();
            req.Payload = payload;
            req.TraceId = someTraceId;

            SystemReference.BillingPointOfSaleInfo billSetInfo = new SystemReference.BillingPointOfSaleInfo();
            billSetInfo.OriginApplication = originApp;

            req.BillingPointOfSaleInfo = billSetInfo;
            req.TargetBranch = "P108154";

            try
            {
                SystemPingPortTypeClient client = new SystemPingPortTypeClient(SystemPingPortTypeClient.EndpointConfiguration.SystemPingPort, WsdlService.SYSTEM_ENDPOINT);
                client.ClientCredentials.UserName.UserName = Helper.RetrunUsername();
                client.ClientCredentials.UserName.Password = Helper.ReturnPassword();
                
                var httpHeaders = Helper.ReturnHttpHeader();
                client.Endpoint.EndpointBehaviors.Add(new HttpHeadersEndpointBehavior(httpHeaders));

                PingRsp rsp = client.service(req);
            }
            catch (Exception e)
            {
                //usually only the error message is useful, not the full stack
                //trace, since the stack trace in is your address space...
                Console.WriteLine("Error : " + e.Message);
            }

**Comment by NirandaG** [comment]
Hi davitgr,
Could you please send us the complete project you have build so that we will review it?
Rgds,
Niranda

**Comment by davitgr** [comment]
Please see the attached projects. Let me know if you want to do a GoTo Meeting.

[triprobin-api.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/1722168/triprobin-api.zip)
[triprobin-core.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/1722169/triprobin-core.zip)

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

I have found quite a few issues while running the project you have provided, So, I have created a very simplified project using .NetCore 2.0 as WepApi. Please find attached the project and it is working fine.

Please use the below Launch URL through Postman after running the project using IISExpress. Please let us know how it goes. Thanks.

http://localhost:3147/api/values/1

[SystemPingTest.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/1725267/SystemPingTest.zip)

**Comment by davitgr** [comment]
Hi Vivek,

Thank you for the solution, I was able to get a response. This was different from the ConsoleApplication solution in GitHub.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

The console application in github is based on .Net Framework, not .net core., That is why the connectivity is different. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

Do you have samples with .net core? Also, is there anything I should know moving forward to be able to work with the APIs?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Please use the project we have shared as the sample for .Net Core. Please let us know how it goes. Thanks.

**Comment by davitgr** [comment]
Are all those wsdl files up to date?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Yes, all those wsdl files are latest. Thanks.

**Comment by davitgr** [comment]
Thanks Vivek. I will let you know how things turn out.

**Comment by davitgr** [comment]
Hi Vivek,

The Wsdl files that you send with the project, all have serviceAsync methods and no service methods. Please let me know what needs to be done. Service is only in the separate SystemReference that you had in the project.

**Comment by davitgr** [comment]
Do you have any updates on the above issue?

**Comment by vivekjyotipramanik** [comment]
Hi  davitgr,

Please give us time till Wednesday to check and remediate the issue. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

Thank you for the update.

**Comment by davitgr** [comment]
Hi Vivek,

I am following up from last week to see if you have found a solution for the issue I was having.

Thank you,

David

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

We are still working on it. We will provide an update as soon as possible. Thanks.

**Comment by davitgr** [comment]
Hi Vivek,

Thank you for the update. Approximately when do you expect to have a
solution? We need this to move forward with development.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

We will try our best to provide an update by couple of days. Thanks.

**Comment by davitgr** [comment]
I have resolved this issue using the serviceAsync methods. I am closing this ticket.

**Comment by javedmail2020** [comment]
Hi davitgr,
Im also facing same error as you, could you please help me how did you resolved it.
