### ISSUE TITLE
Issue in flight search - No more later flights.

### ISSUE THREAD

**Issue by vnokh** [Travelport/travelport-uapi-tutorial-c-sharp#111]
Hi, I am searching for availability of flights but I am receiving the following error

![image](https://user-images.githubusercontent.com/9208445/36423253-2a977054-1665-11e8-93f1-f2989812a23f.png)

Demo application from git repository works fine with default origin and destinations while searching, but its not working if i am changing them to origin and destination within my country, i.e DEL - GOI

I can see flight results on demo website with exactly same request setting, but its not working in c# application.

My Universal API User ID:  Universal API/uAPI6777017844-fb00b734
Branch Code for Galileo (1G): P7009967

I am using pre-production endpoint (https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/) and API credentials.

Kindly help to fix this issue.

Thanks & Regards

**Comment by vivekjyotipramanik** [comment]
Hi vnokh,

This is a valid error response when there are no later flights available as per the search date and markets. Due to limited test data in PreProduction system, we would recommend you to test with MEL - SYD, dates at least 2-3 months from todays date. Please let us know how it goes. Thanks.

**Comment by vnokh** [comment]
Hi Vivek,

I am using Pre Production url but i can see results on demo website with pre procution endpoints, what is wrong if its called via API? and is there any way to get results for any origin and destination in API? i am willing to purchase subscription of this API but not getting any contact information.

Kindly guide.

**Comment by vivekjyotipramanik** [comment]
Hi vnokh,

Please find below the link with details about UAPI contact and sales. Please fill up the form and someone from sales team will contact you. Thanks.

https://developer.travelport.com/euf/assets/developer-network/pdfs/Developer_Details_Contact_Us.pdf

https://developer.travelport.com/app/developer-network/contact-formpage
