### ISSUE TITLE
Get Fare For Individual Way In Two Way Flight Search

### ISSUE THREAD

**Issue by vnokh** [Travelport/travelport-uapi-tutorial-c-sharp#113]
Hi,

I am able to get total fare in response while searching for a two way flight as below:

![ttf](https://user-images.githubusercontent.com/9208445/36726017-45e16f9e-1bde-11e8-8e0c-90e446f79d64.png)

Total fare is 688.08, for two way

Now in AirPriceInfo field of response, I am just getting price for one way as here:

![tf](https://user-images.githubusercontent.com/9208445/36725968-1788da6a-1bde-11e8-8f43-4e2123226e9b.png)

Its AUD 344.04

Now AirPriceInfo field have another field named FareInfo, it have 2 items in it, but none seems to be fare for one way, here is screen:

![if](https://user-images.githubusercontent.com/9208445/36726119-a6de440c-1bde-11e8-99b4-41173cc22c97.png)

My question is, how can get correct fare for individual way in two way flight search?

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi vnokh,

In AirPriceInfo, There should a FareInfo for each of the Segment and the FareInfo would have the property called Amount and TaxAmount. The fare for One Way would be the Amount + TaxAmount. Thanks.
