### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by RedViral** [Travelport/travelport-uapi-tutorial-c-sharp#114]
Hello Travelport Github,

I signed up with travelport api and tried to use my credentials to log into demo.travelportuniversalapi.com. However it's telling my credentials are invalid. I don't understand why this is happening. I just registered weeks and was sent the credentials below. Shouldn't it work off?

Universal API User ID: Universal API/uAPI4748044502-e449a512

Branch Code (TargetBranch) for ProviderName (ProviderCode): Branch Code for Galileo (1G): P7004112

Regards,

**Comment by NirandaG** [comment]
Your account was blocked and we have unblocked it.
Could you please try with your valid credentials or it would block again?
Rgds,
Niranda

**Comment by RedViral** [comment]
Hi Niranda,

Yes I worked. Thank you for your assistance. Could you please give me some guideline on how to develop it in asp.net (Web application). Thanks in advance.

Regards,

**Comment by NirandaG** [comment]
We have sample created for C# and it can be found on the GitHub.
Please refer to this:
https://github.com/Travelport/travelport-uapi-tutorial-c-sharp

Rgds,
Niranda

**Comment by RedViral** [comment]
I have tried to run the application but when I run this application it gets stuck in one code and gives no error message.

<img width="934" alt="error" src="https://user-images.githubusercontent.com/36908788/36769247-57997a26-1c6d-11e8-9ed2-cecf95dc1888.png">

**Comment by NirandaG** [comment]
Have you added your credentials on the config file and please regenerate the WSDL files.
Also please add the below line after client.Endpoint...

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Let us know if this works.
Rgds,
Niranda

**Comment by RedViral** [comment]
I have tried to run the application but when I run this application it gets stuck in one code and gives no error message.

**Comment by RedViral** [comment]
Hi Niranda,

Greetings to you.

Would you please mention on which file do i need to add the below line.
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Thanks.

**Comment by RedViral** [comment]
Hello,

I have been trying to run the sample code from visual C#. Could you please assist me.

Thanks in advance.

![error-travelport-1](https://user-images.githubusercontent.com/36908788/37643661-7e6f2964-2c4b-11e8-94e2-615a67ff8d50.gif)
