### ISSUE TITLE
Credit card details

### ISSUE THREAD

**Issue by davitgr** [Travelport/travelport-uapi-tutorial-c-sharp#122]
What credit card information can I use for air booking in pre production testing? Is there a test number that will validate?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

You can use any credit card information. We do not validate the credit card if it is valid or not. Thanks.

**Comment by davitgr** [comment]
Thanks Vivek

**Comment by davitgr** [comment]
Hi Vivek,

I am getting the error below when I try a random 16 digit credit card number (1234567890123456):

{System.ServiceModel.FaultException`1[UniversalRecordService.ErrorInfo]: Invalid CreditCard , CardNumber invalid number (Fault Detail is equal to UniversalRecordService.ErrorInfo).}

What card details should I use?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Even though we do not validate credit cards, still it needs to be in proper credit card format, like Visa needs to start with 4 etc. and proper expiration date which always should be in future. All these rules are available to any Credit Card API site. Thanks.

**Comment by davitgr** [comment]
Thank you Vivek
