### ISSUE TITLE
Redress Number and Known Traveler Number

### ISSUE THREAD

**Issue by davitgr** [Travelport/travelport-uapi-tutorial-c-sharp#126]
Can you please provide examples of SSR FreeText for Redress Number and Known Traveler Number and the required information needed for each request. I can't find an example anywhere.

**Comment by davitgr** [comment]
Do you have any updates regarding this issue?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Please find below the link with all the details regarding SSR. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Shared_Air_Topics/SSRs_(Special_Service_Requests).htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAssociated%2520Topics%7C_____19

**Comment by davitgr** [comment]
Hi Vivekjyoti,

I tried to figure it out using that link, before I created the ticket. It is hard to understand how the command should be structured in the case of Known Traveler Number or Redress Number. Do you have a code example that I can use to reference?

**Comment by davitgr** [comment]
I understand, but for Redress or Known Traveler numbers, there is a different format, and I know that it is DOCA and not DOCS. So, how should I format the FreeText parameter for these 2 types?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

The FreeText parameter is same for all different kind of ID. You just have to change the ID number. Like say the Knowntraveler number is 12345678 or redress number is 000123, then the format for DOCO will be like the below. Hope this clarifies. The K represents the known Traveler and R represents the redress. Thanks.

For Known Traveler: 

SSR Type="DOCO" HK1//K/12345678/LONDON/14MAR07/USA-1SMITH/JOHNMR Carrier="BA"

For Reddress Number:

SSR Type="DOCO" HK1//R/000123/LONDON/14MAR07/USA-1SMITH/JOHNMR Carrier="BA"


```xml
For the DOCO SSR, the requirements for visa information vary by provider. For all providers, the Supplementary Travel Information document type (e.g., Visa) and Supplementary Travel Information Number (e.g., Visa Number) fields must both be entered, or neither should be entered.

Document types of 'R': Redress Number and 'K': Known Traveler Number can be input in the DOCO SSR with their respective number. Both a Redress Number or Known Traveler Number type always needs a supplementary Travel Information Number.

In a DOCO SSR, a Redress Number must be accompanied by a DOCS SSR for the traveler.

In all cases, validation is performed by the provider.
```

**Comment by davitgr** [comment]
Hi Vivekjyoti,

Thanks, that clarifies it more. But I have 1 question, what is the data in the segment below:

LONDON/14MAR07/USA-1SMITH/JOHNMR

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

London is the place of issue, and DDMMMYY is the date of issue, USA is for which country and the rest is the name of the traveler. Thanks.



SSR Type="DOCS" FreeText="P/GB/S12345678/GB/12JUN63/M/23OCT14/SMITH/JOHN" Carrier="U2"/>

In this example, the FreeText values are:

        P = Passport (Travel Document Type)
        GB = Issuing Country
        123456788 = Document Number
        GB = Passenger Nationality
        12JUN63 = Date of Birth
        M = Male gender
        23OCT14 = Expiry date of passport (Travel Document Type)
        SMITH = Last Name
        JOHN = First Name



SSR Type="DOCA" FreeText="HK1/R/US/1600 SMITH ST/HOUSTON/TX/77001" Carrier="BA"

/R/ designates residence and /US/ designates the country code of the address. The format of the address after the country code is to delimit each address element with a "/".



SSR Type="DOCO" HK1//V/9891404/LONDON/14MAR07/USA-1SMITH/JOHNMR Carrier="BA"

/V/ designates a Visa as the alternate document, London is the place of issue, and DDMMMYY is the date of issue.

Some providers have different requirements for DOCO data.

**Comment by davitgr** [comment]
But we don't need a place of issue or date of issue for the known traveler number or redress number. What do we do in that case?

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

Please provide the data you have for known traveler or redress. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi davitgr,

If that is the only details you have, then use only the number like the below. Thanks.

```xml
For Known Traveler: 

SSR Type="DOCO" FreeText="HK1//K/123456789/SMITH/JOHNMR" Carrier="BA"

For Reddress Number:

SSR Type="DOCO" FreeText="HK1//R/123456789/SMITH/JOHNMR" Carrier="BA"
```

**Comment by davitgr** [comment]
Thank you very much. I really appreciate your help. This is what I was looking for.
