### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Anonymous'.

### ISSUE THREAD

**Issue by YuriyWti** [Travelport/travelport-uapi-tutorial-c-sharp#132]
I'm using trial credentials.
I'm trying to create a GDSQueueListRequest and getting the next error message : 
“The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="AXIS"'.”

Can you help me to fix it?
My Universal API User ID:  Universal API/uAPI2466960806-c3c218d0

**Comment by vivekjyotipramanik** [comment]
Hi YuriyWti,

Could you please check if your credentials are working fine in demosite. If it is not working there as well, Please share your TargetBranch. Thanks.

http://demo.travelportuniversalapi.com/

**Comment by YuriyWti** [comment]
Hi vivekjyotipramanik,

My credentials are not working in a demo site.
I’m getting an error. See below
[cid:image002.png@01D3CDC3.F41574C0]


My Universal API User ID:  Universal API/uAPI2466960806-c3c218d0

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7036544

Thanks,

Yuriy


Yuriy Nikityuk
Point-of-Sale Developer
T: 610.970.5520  |  C: 267.357.5605
ynikityuk@worldtravelinc.com<mailto:ynikityuk@worldtravelinc.com>

[Description: Description: Light-Blue]<http://www.worldtravelinc.com/>

**Comment by NirandaG** [comment]
Hi,
Make sure you enter your username and password correctly in the Demo site. If it is still throwing an error you might need to request new set of credentials.

Rgds,
Niranda

**Comment by YuriyWti** [comment]
Hi,

I got a new set of credentials and sucsessfully got the LowFareSearchRsp response.
But when I'm doing GdsQueueCountReq request I'm getting an Exception "The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic realm="AXIS"'."

Any idea how to fix it?

Thanks,

Yuriy

**Comment by vivekjyotipramanik** [comment]
Hi YuriyWti,

It looks like your credentials are not provisioned for GDSQueue transactions. Please contact your Travelport Account Manager and he/she will be able to provide you with PreProduction credentials with GDSQueue transactions provisioned. Thanks.
