### ISSUE TITLE
ER101 - UNABLE TO PRICE AS BOOKED OR BY LOW FARE FINDER

### ISSUE THREAD

**Issue by dherrerag** [Travelport/travelport-uapi-tutorial-c-sharp#137]
Having ER101 in Air Price Service.

**Comment by vivekjyotipramanik** [comment]
Hi dherrerag,

This is a valid error of the Price is not there any more. Please try dates at least 60-90 days from today's date and try segments like MEL-SYD, DEN-SFO etc. Thanks.
