### ISSUE TITLE
(401) unauthorized Please help..

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-c-sharp#140]
Dear Sir,

Please helps in this issue we are trying to request it's giving error 401 unauthorized....  here is the request & respond...
[ResponseError.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2066289/ResponseError.txt)
[AvailabilitySearchReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2066290/AvailabilitySearchReq.txt)

 We also checked the Travelport DEMO site the credentials are working fine in the demo site.

**Comment by NirandaG** [comment]
Hi,
Could you please send us your username?
Rgds,
Niranda

**Comment by Alex0084** [comment]
Hello Sir,

Here is the UAPI user.

Universal API User ID:  Universal API/uAPI6030405136-ec11970c

Universal API Password:  

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7015254

URLs:  https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by NirandaG** [comment]
Hi,
Could you please try now?
Rgds,
Niranda
