### ISSUE TITLE
Key reference not found for ProviderReservationInfo

### ISSUE THREAD

**Issue by dherrerag** [Travelport/travelport-uapi-tutorial-c-sharp#144]
[Hello]([url]([url](url
[AirCancel.zip](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2104352/AirCancel.zip)

))) @vivekjyotipramanik, I just traying to perform the AirCancel Segments, but I getting the next mesage error. Is there any chance to check my xml Request?

The error:

> **{"Key reference not found for ProviderReservationInfo with key reference +hW6lPmJ0BKACnOxFLAAAA== inside AirSegment"}**

<?xml version="1.0" encoding="ISO-8859-1"?>
<AirCancelReq Version="0" TargetBranch="MYTARGET" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v45_0" OriginApplication="UAPI"/>
<AirReservationLocatorCode xmlns="http://www.travelport.com/schema/air_v45_0">C2NT3E</AirReservationLocatorCode>
<AirSegment xmlns="http://www.travelport.com/schema/air_v45_0" ClassOfService="Z" ProviderCode="1G" TravelTime="204" ArrivalTime="2018-10-19T13:49:00.000-04:00" DepartureTime="2018-10-19T09:25:00.000-05:00" Destination="MIA" Origin="MDE" FlightNumber="30" CabinClass="Economy" Carrier="AV" Group="0" ETicketability="Yes" OptionalServicesIndicator="false" Equipment="320" ProviderReservationInfoRef="+hW6lPmJ0BKACnOxFLAAAA==" GuaranteedPaymentCarrier="No" ProviderSegmentOrder="1" TravelOrder="1" Status="HK" Key="+hW6lPmJ0BKA7JYxFLAAAA==">
<SegmentRemark xmlns="http://www.travelport.com/schema/common_v45_0" Key="+hW6lPmJ0BKAFKYxFLAAAA==">AVIANCA</SegmentRemark>
<FlightDetails TravelTime="204" ArrivalTime="2018-10-19T13:49:00.000-04:00" DepartureTime="2018-10-19T09:25:00.000-05:00" Destination="MIA" Origin="MDE" Equipment="320" Key="+hW6lPmJ0BKA8JYxFLAAAA==" FlightTime="204"/>
</AirSegment>
<AirSegment xmlns="http://www.travelport.com/schema/air_v45_0" ClassOfService="P" ProviderCode="1G" TravelTime="204" ArrivalTime="2018-10-28T18:32:00.000-05:00" DepartureTime="2018-10-28T16:08:00.000-04:00" Destination="MDE" Origin="MIA" FlightNumber="31" CabinClass="Economy" Carrier="AV" Group="1" ETicketability="Yes" OptionalServicesIndicator="false" Equipment="320" ProviderReservationInfoRef="+hW6lPmJ0BKACnOxFLAAAA==" GuaranteedPaymentCarrier="No" ProviderSegmentOrder="4" TravelOrder="4" Status="HK" Key="+hW6lPmJ0BKAGKYxFLAAAA==">
<SegmentRemark xmlns="http://www.travelport.com/schema/common_v45_0" Key="+hW6lPmJ0BKAIKYxFLAAAA==">AVIANCA</SegmentRemark>
<FlightDetails TravelTime="204" ArrivalTime="2018-10-28T18:32:00.000-05:00" DepartureTime="2018-10-28T16:08:00.000-04:00" Destination="MDE" Origin="MIA" Equipment="320" Key="+hW6lPmJ0BKAHKYxFLAAAA==" FlightTime="204"/>
</AirSegment>
<AirSegmentRef xmlns="http://www.travelport.com/schema/air_v45_0" Key="+hW6lPmJ0BKACnOxFLAAAA=="/>
<AirSegmentRef xmlns="http://www.travelport.com/schema/air_v45_0" Key="+hW6lPmJ0BKACnOxFLAAAA=="/>
</AirCancelReq>

Thank you.

**Comment by NirandaG** [comment]
Hi dherrerag,
You need to Serialize the object to get the XML request you are passing.
You could use below method and pass the request to the method:
public static string Serialize(object input)
        {
            if (input == null)
                return null;

            System.Xml.Serialization.XmlSerializer ser = new System.Xml.Serialization.XmlSerializer(input.GetType());

            using (MemoryStream ms = new MemoryStream())
            using (StreamReader sr = new StreamReader(ms))
            {
                ser.Serialize(ms, input);
                ms.Seek(0, 0);
                return sr.ReadToEnd();
            }
        }

Pass the request object into Serialize method and it will return the XML request.

Thank you,
Brgds,
Niranda

**Comment by NirandaG** [comment]
Hi dherrerag,
You need to Serialize the object to get the XML request you are passing.
You could use below method and pass the request to the method:

```public static string Serialize(object input)
{
if (input == null)
return null;

        System.Xml.Serialization.XmlSerializer ser = new System.Xml.Serialization.XmlSerializer(input.GetType());

        using (MemoryStream ms = new MemoryStream())
        using (StreamReader sr = new StreamReader(ms))
        {
            ser.Serialize(ms, input);
            ms.Seek(0, 0);
            return sr.ReadToEnd();
        }
    }
```
Pass the request object into Serialize method and it will return the XML request.

Thank you,
Brgds,
Niranda

**Comment by NirandaG** [comment]
Hi dherrerag,
You need to Serialize the object to get the XML request you are passing.
You could use below method and pass the request to the method:

public static string Serialize(object input)
{
if (input == null)
return null;

        System.Xml.Serialization.XmlSerializer ser = new System.Xml.Serialization.XmlSerializer(input.GetType());

        using (MemoryStream ms = new MemoryStream())
        using (StreamReader sr = new StreamReader(ms))
        {
            ser.Serialize(ms, input);
            ms.Seek(0, 0);
            return sr.ReadToEnd();
        }
    }
Pass the request object into Serialize method and it will return the XML request.

Thank you,
Brgds,
Niranda

**Comment by dherrerag** [comment]
@NirandaG I got it! Please see the attach file.
Thanks

**Comment by vivekjyotipramanik** [comment]
Hi dherrerag,

Please remove the ProviderReservationInfoRef attribute from AirSegment element and give it a try again. Thanks.

**Comment by dherrerag** [comment]
@vivekjyotipramanik thank you so much. It works
