### ISSUE TITLE
Urgent Please help.

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-c-sharp#145]
Dear Sir,

We have issue as showing in the request and response files please help us.

here is our access details also:

Universal API User ID:  Universal API/uAPI6030405136-ec11970c

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7015254
--
URLs:  https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

[xmlresponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2110631/xmlresponse.txt)
[xmlrequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2110632/xmlrequest.txt)

Thanks.

**Comment by Alex0084** [comment]
Any help please? @vivekjyotipramanik @NirandaG

**Comment by NirandaG** [comment]
Hi Alex0084,
Could you please try now? This should work by now.
Rgds,
Niranda

**Comment by Alex0084** [comment]
Thank you for your reply Mr @NirandaG  but i got this new error when i tried I'm attaching it below please. 
![img_19062018_095723_0](https://user-images.githubusercontent.com/31046727/41577408-54b3f528-7395-11e8-802e-61db89bbc3ee.png)

**Comment by Alex0084** [comment]
Do you think something wrong with my request please?

**Comment by NirandaG** [comment]
Hi,
What is the request you are passing? If this is Issue Ticket, please note the ticketing is not allowed in Sanbox/Trial credentials.
Rgds,
Niranda

**Comment by Alex0084** [comment]
Same request as the first comment post Sir.

**Comment by Alex0084** [comment]
Here is the request please 
[xmlrequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/2114037/xmlrequest.txt)

**Comment by NirandaG** [comment]
Hi Alex0084,
Could you please check if the Air Create (book) function is working on Demo site?
https://demo.travelportuniversalapi.com/
Rgds,
Niranda

**Comment by Alex0084** [comment]
Yes sir it's working fine in the demo site please.

**Comment by NirandaG** [comment]
Please send your password to niranda.gunaratna@travelport.com
Rgds,
Niranda

**Comment by Alex0084** [comment]
Sent please check it sir.

Thanks.

**Comment by NirandaG** [comment]
Hi Alex0084,
Please change the Action Status to below and see if that works.
<ActionStatus xmlns="http://www.travelport.com/schema/common_v42_0" Type="ACTIVE" TicketDate="T*" ProviderCode="1G" />
Rgds,
Niranda

**Comment by NirandaG** [comment]
Hi Alex0084,
Please change the ActionStatus to below and see if that works:
```<ActionStatus xmlns="http://www.travelport.com/schema/common_v42_0" Type="ACTIVE" TicketDate="T*" ProviderCode="1G" />```
Rgds,
Niranda

**Comment by Alex0084** [comment]
Working wonderfully.. thanks a lot for your support sir we really do appreciate it much.
