### ISSUE TITLE
Content type problem

### ISSUE THREAD

**Issue by ANevlacsil92** [Travelport/travelport-uapi-tutorial-c-sharp#15]
Hi
I have fixed my previous binding problem which accrued because of the binding scheme. Now I have a new problem with the content type of my response:

"The content type “text/html”; of the response message does not match the content type of the binding (text/xml; charset=utf-8).  If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly" The first 42 bytes of the response were: “Error 404: SRVE0295E: Error reported: 404”.

I’m trying to send a "UniversalRecordSearchRequest" and I found out that there are two different bindings in my App.config, called "UniversalRecordSearchServiceBinding" and "UniversalRecordSearchServiceBinding1". I am using universal_v33_0/UniversalRecord.wsdl as ServiceReference. For UniversalRecordSearchServicePortTypeClient I have to use "UniversalRecordSearchServicePort1" as endpointConfigurationName. I have tried out some others , like "UniversalRecordSearchServicePort" too, but they haven't worked.

Here is a screenshot: After Row 35, where I’ve set a breakpoint, the application switches to "catch".

![screenshot](https://cloud.githubusercontent.com/assets/18415426/14535377/dce2697a-026d-11e6-9be7-ed9f000fb212.png)
 
 Can anybody help me, please?

**Comment by vivekjyotipramanik** [comment]
Hi ANevlacsil92,

Could you please let me know the endpoint URL you are using. To run UniversalRecord services we need to use UniversalService. from the screenshot it looks like you are using GDSQueueService. Please try again after changing it to UniversalService. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ANevlacsil92** [comment]
Hi,

Thank you! problem solved.

Kind Regards
