### ISSUE TITLE
The content type text/html of the response message does not match the content type of the binding (text/xml; charset=utf-8).

### ISSUE THREAD

**Issue by dherrerag** [Travelport/travelport-uapi-tutorial-c-sharp#155]
Hi @vivekjyotipramanik,

Suddenly I'm getting this error trying to import a Universal Record, Do you know the reason ? Thank You.

The content type text/html of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 42 bytes of the response were: 'Error 404: SRVE0190E: File not found: {0}

**Comment by vivekjyotipramanik** [comment]
Hi dherrerag,

Without the exact request and the endpoint you are using, we would not be able to analyze this issue,. Please share the same. Thanks.

**Comment by dherrerag** [comment]
Thanks @vivekjyotipramanik I found the problem and I fixed it.

**Comment by umesh2412** [comment]
@dherrerag  what was the issue i am also getting the same in UniversalRecordRetrieveReq.

error is as below:
The content type text/html of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 42 bytes of the response were: 'Error 404: SRVE0295E: Error reported: 404

My code is as bleow:

TravelxpGalileo.Universal.UniversalRecordRetrieveServicePortTypeClient universalRecordRetrieveServicePortTypeClient = new Universal.UniversalRecordRetrieveServicePortTypeClient("GalileoUniversalRecordRetrieveServicePortType");
                universalRecordRetrieveServicePortTypeClient.ClientCredentials.UserName.UserName = UserName;
                universalRecordRetrieveServicePortTypeClient.ClientCredentials.UserName.Password = Password;

                Universal.UniversalRecordRetrieveRsp universalRecordRetrieveRsp = new Universal.UniversalRecordRetrieveRsp();

                universalRecordRetrieveRsp = universalRecordRetrieveServicePortTypeClient.service(null,null ,universalRecordRetrieveReq);


web.config
<endpoint address="https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService" binding="basicHttpBinding" bindingConfiguration="GalileoWebServicesBinding" contract="Universal.UniversalRecordRetrieveServicePortType" name="GalileoUniversalRecordRetrieveServicePortType" />

**Comment by davemth** [comment]
Hi @umesh2412 

Does your request has an empty value? example TraceId=**""**.
I believe if a tag element in the xml does not have vale so, it wont be added.
