### ISSUE TITLE
Simple ping request in c# not working

### ISSUE THREAD

**Issue by ftcms** [Travelport/travelport-uapi-tutorial-c-sharp#166]
Trying first simple ping request
-- put tested username,password,target branch ( used in api tool) in appconfig
-- changed all client ping url in app.config to point to what I think is correct service 
ie 
from : http://localhost:8080/kestrel/
to:  https://americas-uapi.copy-webservices.travelport.com/B2BGateway/connect/uAPI/
e.g.
      <endpoint address="https://americas-uapi.copy-webservices.travelport.com/B2BGateway/connect/uAPI/SystemService"
        binding="customBinding" bindingConfiguration="CustomServiceBinding"
        contract="SystemService.SystemPingPortType" name="SystemPingPort" />

When I run tutorialone visual studio project it steps through fine until  it gets to

PingRsp rsp = client.service(req);

then I get an error in the immediate window

System.Net Information: 0 : [8924] ConnectStream#35025494 - Sending headers
{
Content-Type: text/xml; charset=utf-8
Authorization: Basic VW5pdmVyc2FsIEFQSS91QVBJMjg5ODA4MDM2Mi04YmI0ODZhNToyWHQ/TXEhN3tC
Accept-Encoding: gzip,deflate
SOAPAction: "http://localhost:8080/kestrel/SystemService"
Host: americas.universal-api.pp.travelport.com
Content-Length: 726
Expect: 100-continue
Connection: Close
}.
System.Net Information: 0 : [8924] SecureChannel#46793998::.ctor(hostname=americas.universal-api.pp.travelport.com, #clientCertificates=0, encryptionPolicy=RequireEncryption)
System.Net Information: 0 : [8924] SecureChannel#46793998 - Left with 0 client certificates to choose from.
System.Net Information: 0 : [8924] Using the cached credential handle.
System.Net Information: 0 : [8924] InitializeSecurityContext(credential = System.Net.SafeFreeCredential_SECURITY, context = (null), targetName = americas.universal-api.pp.travelport.com, inFlags = ReplayDetect, SequenceDetect, Confidentiality, AllocateMemory, InitManualCredValidation)
System.Net Information: 0 : [8924] InitializeSecurityContext(In-Buffer length=0, Out-Buffer length=156, returned code=ContinueNeeded).
System.Net Error: 0 : [8924] Exception in HttpWebRequest#43445707:: - The underlying connection was closed: An unexpected error occurred on a send..
System.Net Error: 0 : [8924] Exception in HttpWebRequest#43445707::GetResponse - The underlying connection was closed: An unexpected error occurred on a send..
Exception thrown: 'System.ServiceModel.CommunicationException' in mscorlib.dll

any clues

**Comment by vivekjyotipramanik** [comment]
Hi ftcms,

Could you please check if your credentials are working fine in the below link. Thanks.
http://demo.travelportuniversalapi.com

**Comment by ftcms** [comment]
yes that works fine..

just checked and I think its actually erring in the client.endpoint line

var httpHeaders = Helper.ReturnHttpHeader();                
 client.Endpoint.EndpointBehaviors.Add(new HttpHeadersEndpointBehavior(httpHeaders));    

httpheaders has a count of 2
1 one has a key if Authorzation and  a long string
2nd one has 'Accept-encoding' and gzip

**Comment by vivekjyotipramanik** [comment]
Hi ftcms,

Could you please confirm if you are basicHttpBinding or customBinding. Please find below the customBinding we are using in the sample code. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/blob/master/ConsoleApplication1/ConsoleApplication1/App.config

**Comment by Bowside** [comment]
Hi, 

I have the same issue, was any resolution provided to this issue?

Error from console app is;
ConsoleApplication1.SystemService.PingReq
Error : An error occurred while making the HTTP request to https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/SystemService. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server.

**Comment by NirandaG** [comment]
Hi Bowside,
Could you please confirm the binding is set to customBinding?
Rgds,
Niranda

**Comment by plastovicka** [comment]
I had the same issue too. I resolved it by inserting this line into the Main function:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
