### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Basic'

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#169]
Using the c# test sample provided I am getting the following response:

"The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm="AXIS"'."

The test credentials are:

Universal API User ID:    Universal API/uAPI3536528924-03555277

https://demo.travelportuniversalapi.com
it login in pre-production but not login in production.

kindly help me to sort out.

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

PreProduction and Production credentials are different. If in demosite your credentials are taking you to PreProduction and not production, that means you have PreProduction credentials only.  To get Production credentials, Please contact your Travelport Account Manager and your Travelport Manager will work with you to get you the Production credentials. Thanks.

**Comment by rehman22** [comment]
Resolved . Thank you
