### ISSUE TITLE
hotel names

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#174]
how can i find hotel names not city name. i want to find hotel by hotel names. in demo it search only by city name .

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

We can search Hotels with Property Names. Please find below the link with the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Search/Hotel_Search_by_Property_Name.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Search%7CHotel%2520Search%2520Modifiers%7C_____2

**Comment by rehman22** [comment]
thank you

**Comment by rehman22** [comment]
can i serach hotel by name ?

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

We can search Hotels with Property Names. Please find below the link with the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Search/Hotel_Search_by_Property_Name.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Search%7CHotel%2520Search%2520Modifiers%7C_____2

**Comment by tytok** [comment]
Me  to

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: vivekjyotipramanik <notifications@github.com>
发送时间: Thursday, July 25, 2019 10:35:33 PM
收件人: Travelport/travelport-uapi-tutorial-c-sharp <travelport-uapi-tutorial-c-sharp@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Travelport/travelport-uapi-tutorial-c-sharp] hotel names (#174)


Hi rehman22,

We can search Hotels with Property Names. Please find below the link with the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Search/Hotel_Search_by_Property_Name.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Search%7CHotel%2520Search%2520Modifiers%7C_____2

―

**Comment by tytok** [comment]
Yes  you can!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ata ur Rehman <notifications@github.com>
发送时间: Thursday, July 25, 2019 4:32:53 PM
收件人: Travelport/travelport-uapi-tutorial-c-sharp <travelport-uapi-tutorial-c-sharp@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Travelport/travelport-uapi-tutorial-c-sharp] hotel names (#174)


can i serach hotel by name ?

―

**Comment by rehman22** [comment]
Tytok i dont understand

**Comment by tytok** [comment]
Can you  give more message?



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ata ur Rehman <notifications@github.com>
发送时间: Friday, July 26, 2019 6:17:08 PM
收件人: Travelport/travelport-uapi-tutorial-c-sharp <travelport-uapi-tutorial-c-sharp@noreply.github.com>
抄送: tytok <songlike@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [Travelport/travelport-uapi-tutorial-c-sharp] hotel names (#174)


Tytok i dont understand

―
