### ISSUE TITLE
FLEX NOT ACTIVE  Error

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#177]
here my req

<LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v42_0" TraceId="91d94ebd-9df0-40d3-adb3-ffc6eca6dbd4" TargetBranch="P3224559" ReturnUpsellFare="true" SolutionResult="true">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI" />
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="KHI" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="DXB" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2019-05-25">
      <SearchExtraDays xmlns="http://www.travelport.com/schema/common_v42_0" DaysBefore="2" DaysAfter="2" />
    </SearchDepTime>
  </SearchAirLeg>
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="DXB" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="KHI" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2019-05-29">
      <SearchExtraDays xmlns="http://www.travelport.com/schema/common_v42_0" DaysBefore="2" DaysAfter="2" />
    </SearchDepTime>
  </SearchAirLeg>
  <AirSearchModifiers>
    <PreferredProviders>
      <Provider xmlns="http://www.travelport.com/schema/common_v42_0" Code="1G" />
    </PreferredProviders>
  </AirSearchModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT" />
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT" />
  <AirPricingModifiers>
    <AccountCodes>
      <AccountCode xmlns="http://www.travelport.com/schema/common_v42_0" Code="-" />
    </AccountCodes>
  </AirPricingModifiers>
</LowFareSearchReq>

and responce --

<SOAP:Fault xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <faultcode>Server.System</faultcode>
  <faultstring>UNABLE - FLEX NOT ACTIVE THIS LOCATION</faultstring>
  <detail>
    <common_v42_0:ErrorInfo xmlns:common_v42_0="http://www.travelport.com/schema/common_v42_0">
      <common_v42_0:Code>258</common_v42_0:Code>
      <common_v42_0:Service>SYSTEM</common_v42_0:Service>
      <common_v42_0:Type>System</common_v42_0:Type>
      <common_v42_0:Description>Flex shopping options not provisioned.</common_v42_0:Description>
      <common_v42_0:TransactionId>E9896E010A0759BA40C759D0DC50C8B2</common_v42_0:TransactionId>
      <common_v42_0:TraceId>91d94ebd-9df0-40d3-adb3-ffc6eca6dbd4</common_v42_0:TraceId>
    </common_v42_0:ErrorInfo>
  </detail>
</SOAP:Fault>

Flex not working

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Flex needs special provisioning. Please contact your Travelport account manager and also raise a ticket in https://my.travelport.com to get provisioned for flex options. Thanks.
