### ISSUE TITLE
.net core project

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#178]
can i add it to .net core project . is it compatible for .net core c#

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Yes, UAPI is compatible with .Net core, but you have to use command to generate the ConnectedServices. We have seen that using the VS 2017 connected services, the proxy classes does not get generated as expected. Thanks.

**Comment by rehman22** [comment]
hi vivekjyotipramanik 

which command ?

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please give it a try using the svcutil command. 

https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x

**Comment by rehman22** [comment]
@vivekjyotipramanik  thank you dear
