### ISSUE TITLE
GDSQueuePlace unexpected errormsg

### ISSUE THREAD

**Issue by ANevlacsil92** [Travelport/travelport-uapi-tutorial-c-sharp#18]
Hello,

last week I successfully sent a QueuePlaceRequest. I started the same application today and it didn't work anymore. It's telling me "UNABLE TO RETRIEVE - CALL HELPDESK"

The code generally works. If I force some errors like not defining a QueueSelector[] at all or trying to place a none existing UR I receive the related error messages.

Here are some screenshots:

This is my main class:
![code1](https://cloud.githubusercontent.com/assets/18415426/14812133/04299076-0b9c-11e6-9be2-a96edc78bc43.JPG)

This is my QueuePlace class:
![code2](https://cloud.githubusercontent.com/assets/18415426/14812135/042a2162-0b9c-11e6-83b5-47553c82132a.JPG)
![code3](https://cloud.githubusercontent.com/assets/18415426/14812134/0429b826-0b9c-11e6-8cd8-c47743d8aa03.JPG)

Here you can see the error messages:
The first one should work but it doesn't.
The other requests lead to the expected errors.
![errormessages](https://cloud.githubusercontent.com/assets/18415426/14812136/042c1210-0b9c-11e6-9e95-9f7c58f93e57.JPG)

Thank you in advance for your help.

**Comment by vivekjyotipramanik** [comment]
Hi ANevlacsil92,

Thank you for your interest in Travelport Universal API. Could you please confirm if the UniversalRecordlocator you are placing in queue exists and in which PCC the UR can be found. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ANevlacsil92** [comment]
Thank you. 

Problem has been solved.

Kind Regards
