### ISSUE TITLE
source code available of demo site?

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#181]
is there any other samples or demo site source code available for developer. 
 if there another sample source available it would be good . thank you

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Could you please let us know the service you are looking the source code for. Thanks.

**Comment by rehman22** [comment]
I was asking about demo travelport api  mvc project which is availabale for demo.  Can i get source code of this demo site.

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Unfortunately, we would not be able to publish the demosite codebase. If this restriction changes, we will provide an update. Thanks.

**Comment by rehman22** [comment]
ok thanks
