### ISSUE TITLE
city name with counrty name and code

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#182]
hello 
        how can i get all  city name and code with country name and code like example below

CountryName":"United Arab Emirates","CountryCode":"AE","CityCode":"AUH","CityName":"Abu Dhabi","AirportCode":"AUH","AirportName":"Abu Dhabi Intl"

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please find below the link with the details. Thanks. 

https://support.travelport.com/webhelp/uapi/uapi.htm#Getting_Started/Design_Considerations/Reference_Data.htm
