### ISSUE TITLE
air price req

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#183]
`<AirPriceReq xmlns="http://www.travelport.com/schema/air_v42_0" TraceId="38836cc7-77cd-4a86-aaee-27d1699574d5" AuthorizedBy="Travelport" TargetBranch="P7087680">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI" />
  <AirItinerary>
    <AirSegment Key="0q6+Gu4R2BKApbfFCAAAAA==" AvailabilitySource="A" Equipment="320" AvailabilityDisplayType="Fare Shop/Optimal Shop" Group="0" Carrier="PK" FlightNumber="213" Origin="KHI" Destination="DXB" DepartureTime="2019-06-28T22:00:00.000+05:00" ArrivalTime="2019-06-28T23:10:00.000+04:00" FlightTime="130" Distance="746" ProviderCode="1G" ClassOfService="I" />
  </AirItinerary>
  <AirPricingModifiers InventoryRequestType="DirectAccess">
    <BrandModifiers ModifierType="FareFamilyDisplay" />
  </AirPricingModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT" BookingTravelerRef="U3E3cnhodlFFMENwQ0M5RA==" Key="U3E3cnhodlFFMENwQ0M5RA==" />
  <AirPricingCommand>
    <AirSegmentPricingModifiers AirSegmentRef="0q6+Gu4R2BKApbfFCAAAAA==" FareBasisCode="ILOWKPK">
      <PermittedBookingCodes>
        <BookingCode Code="I" />
      </PermittedBookingCodes>
    </AirSegmentPricingModifiers>
  </AirPricingCommand>
  <FormOfPayment xmlns="http://www.travelport.com/schema/common_v42_0" Type="Credit" />
</AirPriceReq
`

i have error of no platting carrier
![err](https://user-images.githubusercontent.com/16889407/60173297-d79c4500-9827-11e9-9f54-32442df10a9a.png)

**Comment by rehman22** [comment]
<AirPriceReq xmlns="http://www.travelport.com/schema/air_v42_0" TraceId="38836cc7-77cd-4a86-aaee-27d1699574d5" AuthorizedBy="Travelport" TargetBranch="P7087680">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI" />
  <AirItinerary>
    <AirSegment Key="0q6+Gu4R2BKApbfFCAAAAA==" AvailabilitySource="A" Equipment="320" AvailabilityDisplayType="Fare Shop/Optimal Shop" Group="0" Carrier="PK" FlightNumber="213" Origin="KHI" Destination="DXB" DepartureTime="2019-06-28T22:00:00.000+05:00" ArrivalTime="2019-06-28T23:10:00.000+04:00" FlightTime="130" Distance="746" ProviderCode="1G" ClassOfService="I" />
  </AirItinerary>
  <AirPricingModifiers InventoryRequestType="DirectAccess">
    <BrandModifiers ModifierType="FareFamilyDisplay" />
  </AirPricingModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT" BookingTravelerRef="U3E3cnhodlFFMENwQ0M5RA==" Key="U3E3cnhodlFFMENwQ0M5RA==" />
  <AirPricingCommand>
    <AirSegmentPricingModifiers AirSegmentRef="0q6+Gu4R2BKApbfFCAAAAA==" FareBasisCode="ILOWKPK">
      <PermittedBookingCodes>
        <BookingCode Code="I" />
      </PermittedBookingCodes>
    </AirSegmentPricingModifiers>
  </AirPricingCommand>
  <FormOfPayment xmlns="http://www.travelport.com/schema/common_v42_0" Type="Credit" />
</AirPriceReq>

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please use PlatingCarrier in the request. Please find below the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Air/Air_Pricing/Air_Pricing_with_Plating_Carriers.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Pricing%7CAir%2520Pricing%2520Modifiers%7C_____10

**Comment by rehman22** [comment]
Ok.but this code i copy from demo travelport website demo.. in demo it should add this in request. Because we can check there  uodated request and responce

**Comment by NirandaG** [comment]
Did you try the same in demo site with your credentials?

**Comment by rehman22** [comment]
Yes there same issue was coming..but then its resolve. Thank you for your help..i have one question travelref id in air req or key .. this value is from our side?

**Comment by NirandaG** [comment]
Did you try to add the plating carrier?

**Comment by rehman22** [comment]
![erri](https://user-images.githubusercontent.com/16889407/60511252-f056a000-9cea-11e9-94a7-10e7a26c1e65.gif)

**Comment by rehman22** [comment]
i uploaded gif file .
kindly see 
1 . i am logged in with my cred.  why is no plating error coming.
2. i can not see my log updated on log tab or on xml button click and most of time its blank . kindly guide me whats the problem with demo site

**Comment by NirandaG** [comment]
Please share your username?

**Comment by rehman22** [comment]
I want to see xml of my req and responce

**Comment by rehman22** [comment]
If you will see it show 29 jun old xml showing. Most of time ots not showing xml.. ot shows blank

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

I think there is lots of thread going around. Could you please share the exact issue you are currently facing. Thanks.

**Comment by rehman22** [comment]
> Please share your username?

Universal API/uAPI3536528924-03555277
