### ISSUE TITLE
Departure time cannot be after the Arrival time for Air Segment error in airreq

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#185]
i have air req

`<?xml version="1.0" encoding="utf-8"?>
<AirPriceReq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" TargetBranch="P3224559">
  <BillingPointOfSaleInfo OriginApplication="UAPI" xmlns="http://www.travelport.com/schema/common_v40_0" />
  <AirItinerary xmlns="http://www.travelport.com/schema/air_v40_0">
    <AirSegment Key="4qdjVugB0BKAVqvrtPAAAA==" Equipment="738" Group="0" Carrier="WY" FlightNumber="WY" Origin="MCT" Destination="KHI" DepartureTime="2019-07-10T23:50:00.000+05:00" ArrivalTime="2019-07-11T00:40:00.000+04:00" FlightTime="110" ProviderCode="1G" />
    <AirSegment Key="4qdjVugB0BKAXqvrtPAAAA==" Equipment="789" Group="0" Carrier="WY" FlightNumber="WY" Origin="DXB" Destination="MCT" DepartureTime="2019-07-11T08:40:00.000+04:00" ArrivalTime="2019-07-11T09:50:00.000+04:00" FlightTime="70" ProviderCode="1G" />
  </AirItinerary>
  <AirPricingModifiers PlatingCarrier="WY" xmlns="http://www.travelport.com/schema/air_v40_0" />
  <SearchPassenger Code="ADT" BookingTravelerRef="NlBjTlpW44ZoVktSVWtjWQ=0" xmlns="http://www.travelport.com/schema/common_v40_0" />
</AirPriceReq>`

when i select 0 stop it say kindly check availbily and when i select 1 stop for air req then this "Departure time cannot be after the Arrival time for Air Segment" err come 
 can some body tell me what am i doing wrong
![req](https://user-images.githubusercontent.com/16889407/60469609-cbc0e080-9c76-11e9-8d65-6be09855a262.png)

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Could you please try with a newer schema version like v47 or v48 of UAPI. Thanks.

**Comment by rehman22** [comment]
where can i download it kindly share link .. i have downloaded project from github

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

The github project is not using the latest schema and we are working on to update it. Please use the below link to download the latest schema. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Getting_Started/Universal_API_Schemas_and_WSDLs.htm%3FTocPath%3D_____18

**Comment by rehman22** [comment]
here is latest now  but still same error

`<?xml version="1.0" encoding="ISO-8859-1"?>
<AirPriceReq TargetBranch="P3224559" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v48_0" OriginApplication="UAPI"/>
<AirItinerary xmlns="http://www.travelport.com/schema/air_v48_0">
<AirSegment ProviderCode="1G" FlightTime="110" ArrivalTime="2019-07-17T12:55:00.000+04:00" DepartureTime="2019-07-17T12:05:00.000+05:00" Destination="KHI" Origin="MCT" FlightNumber="324" Carrier="WY" Group="0" Equipment="738" Key="25IcUvOc1BKApXwd1CAAAA=="/>
<AirSegment ProviderCode="1G" FlightTime="70" ArrivalTime="2019-07-17T21:25:00.000+04:00" DepartureTime="2019-07-17T20:15:00.000+04:00" Destination="MCT" Origin="DXB" FlightNumber="611" Carrier="WY" Group="0" Equipment="789" Key="25IcUvOc1BKArXwd1CAAAA=="/>
</AirItinerary>
<AirPricingModifiers xmlns="http://www.travelport.com/schema/air_v48_0" PlatingCarrier="WY"/>
<SearchPassenger xmlns="http://www.travelport.com/schema/common_v48_0" BookingTravelerRef="NlBjTlpW44ZoVktSVWtjWQ=0" Code="ADT"/>
<AirPricingCommand xmlns="http://www.travelport.com/schema/air_v48_0" CabinClass="Economy"/>
</AirPriceReq>`

**Comment by rehman22** [comment]
![Annotation 2019-07-10 015055](https://user-images.githubusercontent.com/16889407/60922027-4ca25c80-a2b5-11e9-82ee-e345215678fe.png)

**Comment by rehman22** [comment]
@vivekjyotipramanik   this below request return 000280 FLIGHT NOT FOUND - CHECK AVAILABILITY 
 error it is 0 stop 


`<?xml version="1.0" encoding="ISO-8859-1"?>
<AirPriceReq TargetBranch="P3224559" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v48_0" OriginApplication="UAPI"/>
<AirItinerary xmlns="http://www.travelport.com/schema/air_v48_0">
<AirSegment ProviderCode="1G" FlightTime="130" ArrivalTime="2019-07-18T23:10:00.000+04:00" DepartureTime="2019-07-18T22:00:00.000+05:00" Destination="KHI" Origin="DXB" FlightNumber="213" Carrier="PK" Group="0" Equipment="320" Key="+VTlXvBAAA/Bq5qBqAAAAA=="/>
</AirItinerary>
<AirPricingModifiers xmlns="http://www.travelport.com/schema/air_v48_0" PlatingCarrier="PK"/>
<SearchPassenger xmlns="http://www.travelport.com/schema/common_v48_0" BookingTravelerRef="NlBjTlpW44ZoVktSVWtjWQ=0" Code="ADT"/>
<AirPricingCommand xmlns="http://www.travelport.com/schema/air_v48_0" CabinClass="Economy"/>
</AirPriceReq>`


and on 1 stop  air req its return "Departure time can not be after the arrival time "

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Could you please raise a ticket in My.Travelport.com for this issue. We will pick it up from there. Thanks.

**Comment by rehman22** [comment]
it have been a week i requested to concern person to generate my id on mytravelport.com . he gave me Pseudo city code (PCC) and Customer number (CIDB) but unfortunately i am not registered

![c81e603c-6cc2-4f6e-ac47-3ba79fb47671](https://user-images.githubusercontent.com/16889407/60926088-dc003d80-a2be-11e9-96ed-f0e393bf081f.jpg)
![fbeff273-2700-4737-a0bb-ceee5244bdaa (1)](https://user-images.githubusercontent.com/16889407/60926116-f20dfe00-a2be-11e9-9387-b73bb7c9113b.jpg)

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please send a mail with the details about the myTravelport issue to your Travelport Account Manager. Thanks.

**Comment by rehman22** [comment]
@vivekjyotipramanik  ok thanks
