### ISSUE TITLE
Unable to add UniversalRecordService travelport reference in c#

### ISSUE THREAD

**Issue by AlbinaAziz** [Travelport/travelport-uapi-tutorial-c-sharp#187]
HI
Please help to find out how to add "https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UniversalRecordService" reference  in my c# project  as it throws an error.

(https://user-images.githubusercontent.com/52534798/61029470-bb2c0b00-a3d8-11e9-8874-0d67b6e2b09c.png)

**Comment by vivekjyotipramanik** [comment]
Hi AlbinaAziz ,

There is no web service URL for UAPI for creating the service reference. Please find below the answer link with detailed explanation. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial/issues/400

**Comment by AlbinaAziz** [comment]
Thank you for solving my issue.
