### ISSUE TITLE
AirReq :departure time cannot be after arrival time

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#189]
![de](https://user-images.githubusercontent.com/16889407/61144400-3df2ba00-a4ee-11e9-9972-a9f55139c59d.png)
`<?xml version="1.0" encoding="utf-8"?>
<AirPriceReq xmlns="http://www.travelport.com/schema/air_v48_0"  TargetBranch="P3224559">
  <BillingPointOfSaleInfo OriginApplication="UAPI" xmlns="http://www.travelport.com/schema/common_v48_0" />
  <AirItinerary xmlns="http://www.travelport.com/schema/air_v48_0">
    <AirSegment Key="Wxm7XvBAAA/BklJyWKAAAA==" Equipment="320" Group="0" Carrier="GF" FlightNumber="753" Origin="BAH" Destination="KHI" DepartureTime="2019-08-13T15:05:00.000+05:00" ArrivalTime="2019-08-13T15:40:00.000+03:00" FlightTime="155" ProviderCode="1G" ClassOfService="Y" />
    <AirSegment Key="Wxm7XvBAAA/BmlJyWKAAAA==" Equipment="320" Group="0" Carrier="GF" FlightNumber="510" Origin="DXB" Destination="BAH" DepartureTime="2019-08-13T18:05:00.000+03:00" ArrivalTime="2019-08-13T20:15:00.000+04:00" FlightTime="70" ProviderCode="1G" ClassOfService="Y" />
  </AirItinerary>
  <AirPricingModifiers PlatingCarrier="GF" xmlns="http://www.travelport.com/schema/air_v48_0" />
  <SearchPassenger Code="ADT" BookingTravelerRef="gr8AVWGCR064r57Jt0+8bA==" xmlns="http://www.travelport.com/schema/common_v48_0" />
  <AirPricingCommand CabinClass="Economy" xmlns="http://www.travelport.com/schema/air_v48_0" />
</AirPriceReq>`

what is mistake kindly tell me

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

I would recommend creating a ticket in My.Travelport.com for this issue and we will pick it up from there. Thanks.

**Comment by rehman22** [comment]
i emailed to concreted person . he will create my id then i will create also there .

and i found this error .. in future if someone have this error this was because of origin destination was wrong .. i mistakenly put origin in destination
