### ISSUE TITLE
hotel request with detail

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#191]
1.can i get hotel detail on first request . i mean i want to display maximum information on my hotel page .
in   demo there is HotelDetailsReq where hotel code sent i want multiple hotel .can i add in this request .

2. i have registered on my travel port waiting for confirmation email. can you tell me how many days it take to reply me by travelport . and what the benefit of mytravelport portal
thanks

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please find below the details. Thanks.

**1.can i get hotel detail on first request . i mean i want to display maximum information on my hotel page .
in demo there is HotelDetailsReq where hotel code sent i want multiple hotel .can i add in this request .**

UAPI does not support HotelDetailsReq with multiple property in a single request. Currently it supports only 1 hotel per request for the HotelDetailsReq. 


**2. i have registered on my travel port waiting for confirmation email. can you tell me how many days it take to reply me by travelport . and what the benefit of mytravelport portal
thanks**

Github is only for development related questions. However we provide some answers to questions related to business logic or transactions, but the best way to get to know about business logic of UAPI or transactions related questions, MyTravelport is the best option. In MyTravelport you can open tickets if you are facing any transaction related issues and someone from our team will pick it up. Please feel free to use github regarding any development related questions.

**Comment by rehman22** [comment]
i see in demo picture url where it came from.. in my response  media item is empty.what if i need image of hotel

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Please find below the link with all the details about Hotel Media and images. Also, there is a separate product called Hotel Content Plus which can provide static data about hotel media and images. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Media/Hotel_Media.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7C_____5
