### ISSUE TITLE
Hotel Rating

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#192]
i am getting AAA in hotel rating. is there Star rating in response 1 star ,2 start,

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

UAPI provide AAA diamond rating and NTM Star rating. Please find below the details about the same. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Search/Hotel_Search_by_Rating.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Search%7CHotel%2520Search%2520Modifiers%7C_____8
