### ISSUE TITLE
hotel HotelSearchAvailabilityRsp

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-c-sharp#193]
where can i find hotel type . like apartment ,hotel ,resort is responce

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

There are 2 kinds of description that can be requested. One is general property description and another one is description using keyword. Also, we can use the Hotel Rate and Rule search to get the details about the Hotel Property. 
Please find below the link with the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Description/HotelDescription.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Description%7C_____0

https://support.travelport.com/webhelp/uapi/uapi.htm#Hotel/Hotel_Rate_and_Rule_Search/Hotel_Rate_and_Rule_Search.htm?Highlight=Condo
