### ISSUE TITLE
AirTicketing recently returning "Error linking ticketing device. INVALID GTID"  after several successful cases 

### ISSUE THREAD

**Issue by zhanfoo13** [Travelport/travelport-uapi-tutorial-c-sharp#199]
Successfully integrated and tested the entire airbooking flow with AirTicketing successfully providing the eTicket numbers. Recently, this has failed returning the above error (refer response below). We already have the printers sets up initially but its now not working. Not sure if this is related to the data refresh in copy as per the support website (_under _Testing Best Practices: Provisioning Issues_). Please advise. Thanks in advance!

<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<ns2:AirTicketingRsp xmlns:ns3="http://www.travelport.com/schema/rail_v48_0" xmlns:ns2="http://www.travelport.com/schema/air_v48_0" xmlns="http://www.travelport.com/schema/common_v48_0" ResponseTime="7192" TransactionId="C9AD540C0A0764780BC2B30489653AC1">

-<ns2:TicketFailureInfo BookingTravelerRef="7G57DEN9JGFIL8W9EIXEZA==" Message="Error linking ticketing device. INVALID GTID" Code="12006">

<ns2:AirPricingInfoRef Key="ef5z224R2BKA6aA7BAAAAA=="/>

<Name Last="GALILEO" Middle="HUSSAIN" First="Hao" Prefix="Mr"/>

</ns2:TicketFailureInfo>

</ns2:AirTicketingRsp>

**Comment by vivekjyotipramanik** [comment]
Hi zhanfoo13,

This is happening cause you do not have ticketing virtual printer not linked with your TargetBranch/PCC. Please contact your Travelport Account Manager to assign and link Virtual ticketing printer with your account. Thanks.

**Comment by zhanfoo13** [comment]
@vivekjyotipramanik **we already have a ticketing printer set up**. As mentioned in my issue, we have had several cases of successful ticketing. It is only recently that it is not able to issue the ticket. Not sure if this is related to the data refresh in copy as per the support website (_under Testing Best Practices: Provisioning Issues). Please advise.

**Comment by vivekjyotipramanik** [comment]
Hi zhanfoo13,

The ticketing printer link was possibly removed. Please contact your account manager to set it up again. We would not be able to setup printer through github. Please contact your Travelport Account Manager or raise a ticket in My.Travelport.com and provisioning team will help you with this. Thanks.
