### ISSUE TITLE
How to generate code from wsdl files?

### ISSUE THREAD

**Issue by miladamirzadeh** [Travelport/travelport-uapi-tutorial-c-sharp#20]
Hi everyone. Thank you for your work.
sorry, it is a beginner question and I'm ashamed to ask this. 
I just don't know how to start a fresh project and add the references, simply adding service reference didn't work for me. I don't want to waste your time explaining this to me, would you please tell a reference to start?

Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi miladamirzadeh,

Thank you for your interest in Travelport Universal API. 
Adding the ServiceReferences should work just fine. Could you please confirm if you downloaded the project https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/tree/master/ConsoleApplication1, if yes, please open the project in Visual Studio, right click on the project in visualStudio and go to Add->Add Service References, once the ServiceReference window is open, please specify the path of the WSDL file inside the project folder, specify the name and click on OK. This should generate the ServiceReferences.

The project already has the service  references created, so, this should be a good starting point.

Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by miladamirzadeh** [comment]
Thank you for your response. Yes, I finally could add the references but two other problems appeared which I'll discuss in another issue.

Thank you so much.
