### ISSUE TITLE
Search LFsearch / AirPrice flight time is different with AirCreateReservation (5 mins difference)

### ISSUE THREAD

**Issue by zhanfoo13** [Travelport/travelport-uapi-tutorial-c-sharp#200]
AirCreateReservation returns warning 'Segment sync error. Flight times returned from the carrier do not match the flight times requested.' and flight time is 2019-10-28 02:25PM. Please advise. Thanks!

Refer "LowFareSearchRsp.xml", line 89~92

<ns2:AirSegment Group="0" Carrier="MH" FlightNumber="619" ETicketability="Yes" Equipment="738" ChangeOfPlane="false" OptionalServicesIndicator="false" AvailabilitySource="P" Origin="KUL" Destination="SIN" DepartureTime="2019-10-28T14:20:00.000+08:00" ArrivalTime="2019-10-28T15:30:00.000+08:00" ParticipantLevel="Secure Sell" LinkAvailability="true" PolledAvailabilityOption="Cached status used. Polled avail exists" AvailabilityDisplayType="Fare Shop/Optimal Shop" FlightTime="70" Distance="196" Key="ohDho28Q2BKAfB4CAAAAAA==">           <ns2:AirAvailInfo ProviderCode="1G"/>           <ns2:FlightDetailsRef Key="ohDho28Q2BKAgB4CAAAAAA=="/>       </ns2:AirSegment>

Refer "AirPriceRsp.xml", line 5~7

<ns2:AirSegment Group="0" Carrier="MH" FlightNumber="619" ClassOfService="Q" Equipment="738" ChangeOfPlane="false" OptionalServicesIndicator="true" AvailabilitySource="S" ProviderCode="1G" Origin="KUL" Destination="SIN" DepartureTime="2019-10-28T14:20:00.000+08:00" ArrivalTime="2019-10-28T15:30:00.000+08:00" ParticipantLevel="Secure Sell" PolledAvailabilityOption="O and D cache or polled status used with different local status" AvailabilityDisplayType="Fare Specific Fare Quote Unbooked" FlightTime="70" TravelTime="70" Distance="196" Key="ohDho28Q2BKAji5CAAAAAA==">           <ns2:CodeshareInfo OperatingCarrier="MH">Malaysia Airlines Berhad</ns2:CodeshareInfo>           <ns2:FlightDetails Key="ohDho28Q2BKAki5CAAAAAA==" FlightTime="70" TravelTime="70" Distance="196" Origin="KUL" Destination="SIN" DepartureTime="2019-10-28T14:20:00.000+08:00" ArrivalTime="2019-10-28T15:30:00.000+08:00"/>       </ns2:AirSegment>

Refer "AirCreateReservationRsp.xml", line 7~9

<ns3:AirSegment Group="0" Carrier="MH" CabinClass="Economy" FlightNumber="619" ClassOfService="Q" ETicketability="Yes" Equipment="738" GuaranteedPaymentCarrier="No" OptionalServicesIndicator="false" ProviderCode="1G" Origin="KUL" Destination="SIN" DepartureTime="2019-10-28T14:25:00.000+08:00" ArrivalTime="2019-10-28T15:30:00.000+08:00" TravelTime="65" Distance="196" Key="ohDho28Q2BKAvy6CAAAAAA==" Status="HS">               <ns3:FlightDetails Key="ohDho28Q2BKACz6CAAAAAA==" Equipment="738" OriginTerminal="M" DestinationTerminal="2" AutomatedCheckin="false" FlightTime="70" TravelTime="65" Origin="KUL" Destination="SIN" DepartureTime="2019-10-28T14:25:00.000+08:00" ArrivalTime="2019-10-28T15:30:00.000+08:00"/>           </ns3:AirSegment>

**Comment by vivekjyotipramanik** [comment]
Hi zhanfoo13,

This seems like an issue. Could you please create a ticket in My.Travelport.com and we will pick it up from there. Thanks.

**Comment by zhanfoo13** [comment]
@vivekjyotipramanik thanks for your response. This has already been raised.
