### ISSUE TITLE
Schema for the current request air_v40_0 will expire in 47 day(s). Please update to latest version.

### ISSUE THREAD

**Issue by Nuttapol01** [Travelport/travelport-uapi-tutorial-c-sharp#201]
Hi, 
i have ResponseMessage  :  Schema for the current request air_v40_0 will expire in 47 day(s). Please update to latest version.

```
<AirTicketingRsp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" TransactionId="xxxxxxxxxxxxxxxxx" ResponseTime="1369">
  <ResponseMessage Code="16400" Type="Warning" xmlns="http://www.travelport.com/schema/common_v40_0">Schema for the current request air_v40_0 will expire in 47 day(s). Please update to latest version.</ResponseMessage>
  <TicketFailureInfo Code="12008" Message="Host error during ticket issue. LINKAGE/OPTIONS CHANGED - UPDATE SDPT" BookingTravelerRef="xxxxxxxxxxxxxxxxx" xmlns="http://www.travelport.com/schema/air_v40_0">
    <AirPricingInfoRef Key="xxxxxxxxxxxxxxxxx" />
    <AirPricingInfoRef Key="xxxxxxxxxxxxxxxxx" />
    <AirPricingInfoRef Key="xxxxxxxxxxxxxxxxx" />
    <Name Prefix="MR" First="ABC" Last="DEF" xmlns="http://www.travelport.com/schema/common_v40_0" />
  </TicketFailureInfo>
</AirTicketingRsp>
```

I have some questions:
- i should generate new version wsdl (new Schema)?
- If i generate new version wsdl  , it will effect on my code ?

**Comment by vivekjyotipramanik** [comment]
Hi Nuttapol01,

You have to download new schema from the below location which includes both WSDL and XSD files and you have to generate proxy files as per your requirements. Thanks.

https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V19.2.0.12.zip

**Comment by Nuttapol01** [comment]
Hi vivekjyotipramanik,
i generate new Schema(air_v49_0) ,when i Request AirCreateReservationReq,I have Error ResponseMessage but Schema(air_v40_0) it works.

i attach file Request and Response for you . Thank.
[reservationReq_V40.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/3966680/reservationReq_V40.txt)
[reservationReq_V49.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/3966681/reservationReq_V49.txt)
[reservationRsp_V40.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/3966683/reservationRsp_V40.txt)
[reservationRes_V49.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/3966684/reservationRes_V49.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Nuttapol01,

As this is a transaction issue, Please create a ticket in My.Travelport.com and we will pick it up from there. Thanks.

**Comment by Nuttapol01** [comment]
Hi vivekjyotipramanik,
Today , I requested AirCreateReservationReq Schema(air_v49_0), It's working but sometimes I have Error ResponseMessage.
It seems PreProduction system error sometimes.

Thanks.
