### ISSUE TITLE
Unsuccessful primary host transaction causing reservation failure.

### ISSUE THREAD

**Issue by kumudunsamarakoon** [Travelport/travelport-uapi-tutorial-c-sharp#204]
Hi,
When I am trying to create an air reservation by using AirCreateReservationReq, I am getting "Unsuccessful primary host transaction causing reservation failure." 
Here are the account details, 
Target Branch Code: P7129438
User Name: Universal API/uAPI1583164056-159aa2e3

When I am trying to use the demonstration environment, I am getting "Transaction Error: Procedure/5012"  error.

**Comment by vivekjyotipramanik** [comment]
Hi kumudunsamarakoon,

The account has been rebuilt. Please try again. Thanks.

**Comment by kumudunsamarakoon** [comment]
Hi @vivekjyotipramanik,
Now it's working. Thanks a lot.
