### ISSUE TITLE
Error unmarshalling message body: Missing required attribute "Host"

### ISSUE THREAD

**Issue by salmanelahi93** [Travelport/travelport-uapi-tutorial-c-sharp#208]
Hi Vivek,

While we executing CreateTerminalSession API, I'm receiving following error:

**"Error unmarshalling message body: Missing required attribute "Host"**

I dont know, from where I can found Host value. Please help.

Following is the req xml:

```
<?xml version="1.0" encoding="utf-16"?>
<CreateTerminalSessionReq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" TargetBranch="xxxxxx">
  <BillingPointOfSaleInfo OriginApplication="UAPI" xmlns="http://www.travelport.com/schema/common_v33_0" />
  <OverridePCC ProviderCode="1G" PseudoCityCode="xxxx" xmlns="http://www.travelport.com/schema/common_v33_0" />
</CreateTerminalSessionReq>
```

When I pass just dummy string value "xxxxxx" to the param Host, I found the following exception:

**"No enum constant com.g2switch.core.service.Provider.xxxxxx"**

**Comment by vivekjyotipramanik** [comment]
Hi,

Could you please try with the below request. Please use your correct TaregtBranch. Thanks.

```xml
<?xml version="1.0" encoding="utf-16"?>
<CreateTerminalSessionReq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" TargetBranch="xxxxxx">
  <BillingPointOfSaleInfo OriginApplication="UAPI" xmlns="http://www.travelport.com/schema/common_v33_0" />
</CreateTerminalSessionReq>
```

**Comment by salmanelahi93** [comment]
**Error unmarshalling message body: Missing required attribute "Host"**

Receiving above error when I tried your xml. I don't know what value I have to pass in Host parameter.

**Comment by vivekjyotipramanik** [comment]
Hi,

Could you please create a ticket in My.Travelport.com and we will pick it up from there. Thanks.

**Comment by salmanelahi93** [comment]
https://demo.travelportuniversalapi.com/

Do you want to create ticket from here?

Is it possible to create ticket from demo site?

**Comment by salmanelahi93** [comment]
I found following error when trying to create ticket on demo site (My.Travelport.com):

**Purchasing an itinerary is not available on the Production version of the Demo site.**

**Comment by vivekjyotipramanik** [comment]
Hi salmanelahi93,

Please create ticket  in https://My.Travelport.com, not the demosite. You can't create support ticket in demosite. Also, I meant support ticket , not airline ticket. Thanks.

**Comment by salmanelahi93** [comment]
This is showing on support ticket screen (I'm from Pakistan):

**Request submission not available due to security constraints**

![image](https://user-images.githubusercontent.com/5991679/98783952-28f8a480-241c-11eb-9593-30676bbf131b.png)

**Comment by vivekjyotipramanik** [comment]
Hi salmanelahi93,

Please reach out to your Travelport Account Manager to provide you access in My.Travelport.com to create support ticket. Thanks.

**Comment by salmanelahi93** [comment]
Hi Vivek,

CreateTerminalSession API executed successfully after passing value **"1G"** to the parameter **"Host"**.

**Comment by salmanelahi93** [comment]
Now we facing issues in actual "**TerminalService**". Receiving following error:

**"Name is null"**

We are not able to find property **"Name"**. Following is the xml request:

```
<?xml version="1.0" encoding="utf-16"?>
<TerminalReq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" TargetBranch="PXXXXXX">
  <BillingPointOfSaleInfo OriginApplication="UAPI" xmlns="http://www.travelport.com/schema/common_v33_0" />
  <HostToken xmlns="http://www.travelport.com/schema/common_v33_0">ZvuhYvlsIuN8GB1+ylEeuRThGYp1BUBb5dik/qVCBTK7a0OVT/Wy0bGSsrh2g6vhj3j5BDNiYqJ6oENps+yO0MB0vMb0bvaZULJYa92mekxYdpUrFLptxkU6AgfRxIjy</HostToken>
  <TerminalCommand xmlns="http://www.travelport.com/schema/terminal_v33_0">I</TerminalCommand>
</TerminalReq>
```
