### ISSUE TITLE
Dealing with error "the provided URI scheme 'https' is invalid; expected 'http'"

### ISSUE THREAD

**Issue by miladamirzadeh** [Travelport/travelport-uapi-tutorial-c-sharp#21]
Hi dear contibutors,
The console project you provided works fine. But I wanted to start from scratch to understand the whole project.
I started an MVC project in VS2015, added references and started coding. My first try was to use PingReq object to ensure connectivity as sample project recommends. 

I got the error **the provided URI scheme 'https' is invalid; expected 'http'**. After googling I found the solution below.
```
var binding = new BasicHttpBinding("SystemPingPort") {Security = {Mode = BasicHttpSecurityMode.Transport,Transport = new HttpTransportSecurity()
            {
                Realm = "AXIS",ClientCredentialType = 
                    HttpClientCredentialType.Basic
            } }};

            var client = new SystemPingPortTypeClient(binding,new EndpointAddress(WsdlService.SYSTEM_ENDPOINT))
            {
                
                ClientCredentials =
                {
                    UserName = {UserName = ProjectConstants.Username, Password = ProjectConstants.Password}
                }
                
                
            };
```

Where Username and Password are the credentials that are provided by Travelport API. I couldn't find out what is the difference between my project and sample console application. I even tried to make app.config from console application as web.config(With web considerations) but no success. 
Would you please tell me your suggestions? And why above solution works?

**Comment by vivekjyotipramanik** [comment]
Hi miladamirzadeh,

Could you please confirm if you used the trial credentials inside the app.config.
Also, Please confirm the endpoint URL you are using.

BasicHttpBinding generally has problems with uAPI request and response. Please use customBinding and CustomServiceBinding in the app.config provided in the ConsoleApplication. 

Also, if your account is locked, then also you might receive this error. Please try your credentials in demo.travelportuniversalapi.com and please check if it is locked. 

Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
