### ISSUE TITLE
Error retrieving AccessProfile

### ISSUE THREAD

**Issue by ANevlacsil92** [Travelport/travelport-uapi-tutorial-c-sharp#22]
Hello.

when I started my script today, which worked yesterday, I received an errormessage. I don't know why it isn't working anymore, Could it be possible that my Credentials have expired?

![screenshot](https://cloud.githubusercontent.com/assets/18415426/15185763/bff2b38c-179a-11e6-82b4-b5c820e7d5bb.JPG)

**Comment by vivekjyotipramanik** [comment]
Hi ANevlacsil92,

Could you please provide the TargetBranch and Username. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ANevlacsil92** [comment]
Hi,

Universal API/uAPI8583448119-046bc040
P7053012

Thanks. Kind Regards.

**Comment by miladamirzadeh** [comment]
It seems that Travelport has issues on web service on May 11 globally. It should be okay now.

**Comment by ANevlacsil92** [comment]
it is. Thank you.

**Comment by miladamirzadeh** [comment]
You are welcome. Would you please close this issue. Thanks.

**Comment by ANevlacsil92** [comment]
close
