### ISSUE TITLE
Total Price in LowFareSearch ReS 

### ISSUE THREAD

**Issue by YousifALF** [Travelport/travelport-uapi-tutorial-c-sharp#220]
Hello,  
How can I display the total price from LowFareSearch Function? 
just like the image below, I couldn't find it In the LowFareSearchRes
![Img](https://user-images.githubusercontent.com/30030949/113017009-b4829000-9187-11eb-8965-db2700a1d370.png)

**Comment by YousifALF** [comment]
Hello, 
Any help so far?

**Comment by RicOsiro** [comment]
Hi,

the xpath is the LowFareSearchRsp/AirPricePointList/AirPricePoint@TotalPrice

More details about the response structure
https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_by_Price_Points.htm?TocPath=Air%257CAir%2520Shopping%2520and%2520Booking%257CLow%2520Fare%2520Shopping%257C_____4

**Comment by YousifALF** [comment]
@RicOsiro
Thanks issue solved
