### ISSUE TITLE
Price Breakdown For Air Availability

### ISSUE THREAD

**Issue by miladamirzadeh** [Travelport/travelport-uapi-tutorial-c-sharp#23]
Hi,
Today I encountered a problem with getting prices for list of flights. As [documentions](https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Shopping_and_Booking.htm) states there is commonly two ways to get prices for a flight.

1. Using LowfareSearchReq to request the data when fare is more important than schedule.
2. Using AirAvailabilitySearchReq follows with an AirPrice request.

The first approach works fine and returns information as we wanted. But there is some problems with AirPrice request. 

1. Sometimes we get results from LowFareSearchRsp with details about Class of service and CabinCalss but AirPrice throws the exception "No Valid Fair Found"
2. How we can breakdown the price for different class of services of a flight. AirPrice always return a unique amount for all class of services, sometimes exception.

**Comment by vivekjyotipramanik** [comment]
Hi miladamirzadeh,

As you are using Test Environment, Sometimes the LowFareSearch returns with price which might be unavailable, that is why, during Price it shows No Valid Fare.

The AirPrice will return the price based on which ClassofService you are asking the price for.
In AirPriceRsp/AirPricingSolution all the price bearkdown should be there, but to get price for a different classOfService we need to run AirPrice with that ClassOfService.

Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by miladamirzadeh** [comment]
Hi vivekjyotipramanik,
Thank you for your response. 
Yes, I can add ClassOfService to AirPriceModifiers, But I have two problems:

1. First, it is slow. I have to create an AirPriceReq for each air segment, sometime for (15 air segments it takes about 20 seconds). When I call the service for multiple air segments it throws the exception 
`000279 VERIFY DATE SEQUENCE IN ITINERARY`.

2. I want to get the information about prices and save them locally, with the supposition that prices are not frequently updated for a flight. Am I right?

Thanks.

**Comment by miladamirzadeh** [comment]
Hi vivekjyotipramanik,
Another issue I faced with today, is that changing the ClassOfService property of an air segment does not bring the price for that segment. Prices are always the same. What is the right way to ask for another class of service as well as another Cabin Class in AirPriceReq?

**Comment by vivekjyotipramanik** [comment]
Hi miladamirzadeh,

The recommended way is, First step LowFareSearch and based on the selection/selected AirPricingSolution, please do AirPrice based on the AirSegment in a particular AirPricingSolution/AirPricepoint in LowFareSearch.

As per my humble opinion, for performance integrity, it is not practical to run AirPriceReq for all the ClassOfService returned in LowFareSearch.

Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by miladamirzadeh** [comment]
Thanks.
