### ISSUE TITLE
AirPricing Renew FiledFare

### ISSUE THREAD

**Issue by ANevlacsil92** [Travelport/travelport-uapi-tutorial-c-sharp#31]
Hallo,

I want to renew the FiledFares of a Flight. In the GDS I would simply use one of the comments you can see in the screenshot... e.g ">FQP1" to renew the first one.

![galileoscreenshot](https://cloud.githubusercontent.com/assets/18415426/16384043/dcb72dba-3c87-11e6-8f31-5d40bddf42dc.JPG)

 Is it possible to simulate that input using the API? I know where to find the AirPricingInfo in my GDSEnterQueueRsp but I have no idea how to renew them. Please help.

Many thanks in advance.

**Comment by vivekjyotipramanik** [comment]
Hi ANevlacsil92,

I will check and will provide an update soon. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ANevlacsil92** [comment]
Hi,

are there any updates?

Kind Regards.

**Comment by vivekjyotipramanik** [comment]
Hi ANevlacsil92,

Apologies for the delayed response. If we don't response within couple of days, Please feel free to ask for updates. 

Regarding your question, Could you please confirm if you asking to reprice the fare. Please find below the link with all the details regarding reprice. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Automated_Exchanges/AutomatedExchanges.htm%3FTocPath%3DAir%7CAutomated%2520Exchanges%7C_____0

Thanks & Regards
Vivekjyoti Pramanik
