### ISSUE TITLE
SearchAirLeg.Leg.SearchOrigin.SetValue(...) throws a null reference exception

### ISSUE THREAD

**Issue by imAliAsad** [Travelport/travelport-uapi-tutorial-c-sharp#33]
Hi Support Team,

I've been trying to call the **CreateAirLeg** method.

`AirReq air = new AirReq();
var result = air.CreateAirLeg("BQH", "BOM");`

Soon i debug the application, a null exception throws.

![image](https://cloud.githubusercontent.com/assets/10113717/16410235/fd5e97ca-3d3a-11e6-93ce-ef69ed05875d.png)

Can you tell me, what i'm missing here?

Also i need a little assistance, can you show me code samples which used in https://demo.travelportuniversalapi.com/Home to search and book flights. Thanks in advance.

Regards,
Ali Asad

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Hopefully this issue is also resolved now. We are closing this issue. Please feel free to  reopen if you are still getting the issue. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Ali I am having the same issue. Did you find the solution?
