### ISSUE TITLE
Error From Host: No availability on chosen flight 

### ISSUE THREAD

**Issue by imAliAsad** [Travelport/travelport-uapi-tutorial-c-sharp#34]
Hello Support Team,

I download sample travelport project of C# on github (ConsoleApplication1). I've been trying to search available flight from (SKT to LCY). But every time same error pop up 
(**Error From Host: No availability on chosen flight**).  See the below error message.

![image](https://cloud.githubusercontent.com/assets/10113717/16420788/1d924510-3d6c-11e6-968a-7c86032723fc.png)

I tried to put same parameter in demo.travelport site. It successfully displayed the following result. see the below image. 

![image](https://cloud.githubusercontent.com/assets/10113717/16420843/53c47c34-3d6c-11e6-915c-25c266277ccf.png)

How to display available flight result as it displayed on demo.travelport site. I'm in bit hurry because i have to show a working demo to my manager ASAP. Thank you

Kind Regards,
Ali Asad

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Could you please provide me the xml request you are sending you the C# application. The error is a valid error and comes up when there is no availability on the flights. Could you please use the same Arrival and departure dates in the project and it should work. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Another thing, in c# application you are using PreProduction endpoint and demo.travelport.com you are using Production. PreProduction has only test data and it is quite possible that the flights are not available in the test system. Please use PreProduction in demo.travelport.com and you should see the same results there as well. Please try with different Market like MEL to SYD or DEN to ATL and it should work fine. To change to PreProduction in demosite, please click on the Production button and you should see options to change to PreProdcution. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
H Vivek,

Thank you for helping me again. I really appreciate your quick response. I convert my **origin**:MEL and **dest**:SYD. I gave from and to date of tomorrow. Result show successfully on demo.travelport.com with pre-production. 

![image](https://cloud.githubusercontent.com/assets/10113717/16431754/7109165e-3d9b-11e6-8b16-2388da90ddf5.png)

But same parameters do not working in code. I think I'm missing something. But I can't guess what it is. Below are code snippets.

**Origin & Destination**
` private string origin = "MEL";
  private string destination = "SYD";
`

**SearchAirLeg**
`     
           
            SearchAirLeg outbound = AirReq.CreateSearchLeg(origin, destination);
            AirReq.AddSearchDepartureDate(outbound, Helper.daysInFuture(1));
            AirReq.AddSearchEconomyPreferred(outbound);

            //coming back
            SearchAirLeg ret = AirReq.CreateSearchLeg(destination, origin);
            AirReq.AddSearchDepartureDate(ret, Helper.daysInFuture(1));
            //put traveller in econ
            AirReq.AddSearchEconomyPreferred(ret);   
`
Can you tell me how to get requested xml, so I may help you to understand the problem more quickly. Thank you sir.

Kind Regards,
Ali

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Please do not use tomorrow's date in any test scenarios. Please use dates at least 15 days from now.
Also, Please do not use same departure and return dates. Please give at least 3-5 days gap between return dates. Also Have you checked the Preferred Carrier used in the c# application, Please comment out the PreferredCarrier in c# and try again. If it is still not working, Please send me your username,password and TargetBranch in my email id and I will check with them. For me, the c# application is working absolutely fine. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Sorry its not working again. I set 16 days from now in origin and set 3 days more in destination. it is working fine in demo.travelport.com but shows error in consoleapplication1. I sent you credentials on your email please check it. I hope you'll find the resolution. Thank you for being good support. Bless you

Regards,
Ali

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

I have tried with your credentials in demosite and it is getting GTID error over there. It is a problem with your credentials. Looks like your credentials does not have any valid GTID. We will fix your credentials and will provide an update as soon as possible. Thanks.

```xml
<SOAP:Fault xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <faultcode>Server.System</faultcode>
  <faultstring>Please provide a valid Static GTID.</faultstring>
  <detail>
    <common_v35_0:ErrorInfo xmlns:common_v35_0="http://www.travelport.com/schema/common_v35_0">
      <common_v35_0:Code>10</common_v35_0:Code>
      <common_v35_0:Service>SYSTEM</common_v35_0:Service>
      <common_v35_0:Type>System</common_v35_0:Type>
      <common_v35_0:Description>Transaction failure.</common_v35_0:Description>
      <common_v35_0:TransactionId>98DDB1090A0764776B1F7E73570CAF09</common_v35_0:TransactionId>
      <common_v35_0:TraceId>10b9d694-3e35-4300-9f43-7545415c9c17</common_v35_0:TraceId>
    </common_v35_0:ErrorInfo>
  </detail>
</SOAP:Fault>
```

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Thank you sir. That's good to hear, that problem would be resolve. When would the update of my credentials are expected? Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Our internal team will work on this and I will provide an update as soon as possible.
Generally within one day you can expect a response. 

But, through github we do not support urgent and critical issues. If this is really urgent and critical to your need, Please open a ORS ticket in https://support.travelport.com/tdssupport/main.asp and a support team analyst will assist you. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

We have rebuilt the credentials. Could you please try again. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Yes it is working fine now. Thank You sir. I really appreciate your help.

Stay Blessed,
Ali Asad
