### ISSUE TITLE
How to get pricing of a flight and how to book a flight

### ISSUE THREAD

**Issue by imAliAsad** [Travelport/travelport-uapi-tutorial-c-sharp#35]
Hello Support Team,

Please pardon me to post basic issue. 
Would you like to share a code sample which explain

- How to get pricing of a flight

- How to book a flight

Many Thanks,
Ali Asad

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

The sample is already there in the C# Console Application One. Please find below the link. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/tree/master/ConsoleApplication1

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Hi @vivekjyotipramanik , Hope you're fine. Thank you again for replying to my this issue. Yes i know sample is already available. Actually I'm asking, would help me to demonstrate what values do we need to pass in parameters of method AirBook.
`AirBook(AirService.AirPricingSolution lowestPrice, AirService.AirItinerary airItinerary)`

I don't understand what i need to put in 'lowest Price' and 'airlitnerary'. 

in the sample project there is a method ` public void Availability(){..}` which show list of all available flights from point A to point B. this method is simple and straight forward with no parameters. It helps me to understand code written in the method. 
But in case of `AirBook(AirService.AirPricingSolution lowestPrice, AirService.AirItinerary airItinerary)`
method, I do not understand these parameters. 

Hope you understand what i'm trying to say. Thanks in Advance

**Comment by imAliAsad** [comment]
Same goes with finding pricing of flights too

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

If you run the code in debugger mode, you will see the data we are passing there, we are actually taking the LowFareSearch and then from the LowfareSearch we are comparing the Lowest fare available and we are sending that one along with the Segments which has the lowest fare. 

If it is not clear, I believe we should schedule a call, cause it is quite impossible to explain it by mail/github. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Yes I understand. Thank you again for your time. I'm working on it. if i need to schedule a call. I'd let you know on email.

Many Thanks Sir

**Comment by imAliAsad** [comment]
Thank you @vivekjyotipramanik . I able to see the price now. Pardon me for asking naive questions.

Many Thanks,
Ali Asad

![image](https://cloud.githubusercontent.com/assets/10113717/16504385/208fe472-3f31-11e6-800c-545da2244b98.png)
