### ISSUE TITLE
please help with "error linking ticketing device Invalid GTID"

### ISSUE THREAD

**Issue by nandoDev** [Travelport/travelport-uapi-tutorial-c-sharp#36]
Hello  VivekJyotiPramanik,

I am working in a project which implements practically all the Air flow of Universal Api. Im trying to set "Ticketing" after have set succesfully an AirBooking. But Im getting this failiuremessage: "Error linking ticketing device Invalid GTID", or in another times also the error message: "Message   "com.g2switch.common.service.exception.ServiceException: Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: Error retrieving AccessProfile Unable to retrieve enough Dynamic GTIDs for this transaction"  string". I have read about to set a linked printer in the admin portal but we are using preproduction credentials, we have not access to admin portal. For any help very thanks!

**Comment by vivekjyotipramanik** [comment]
Hi nandoDev,

Ticketing cannot be done without virtual ticketing Printer. 
Could you please confirm if you already signed a contract with Travelport, If so Please contact your Travelport Account Manager to setup the ticketing Printer. 

If you have not signed a contract yet, Please provide me your Company Details, Contact details and Contact number and a Travelport Sales Team Representative will contact your regarding the procedure. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by nandoDev** [comment]
Mr Vivekjyoti Pramanik,
Thanks for your answer, my manager will be keeping the contact,
