### ISSUE TITLE
Error: Message from Galilo:  Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: Exception ReturnedERR: AGENT ID - GALILEOWith the Dynamic GTID list of:A80AD4

### ISSUE THREAD

**Issue by imAliAsad** [Travelport/travelport-uapi-tutorial-c-sharp#38]
Hellp Support team,

I was debugging ConsoleApplication1 project and found a **service exception** on this line of code in AirBook() method.

`reservationRsp = client.service(null, reservationReq);`

**Error message:**
![image](https://cloud.githubusercontent.com/assets/10113717/16545288/75480afc-413f-11e6-9816-384eeecc20f8.png)

Kindly help me on this. Thanks in advance

Regards,
Ali Asad

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Could you please provide the Username and TargetBranch you are using so that we can check the issue and resolve it. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
Hi @vivekjyotipramanik ,

Thank you for looking in the issue. here are username and targetbranch

Universal API User ID:  Universal API/uAPI1378167135-632a12d1
Branch Code for Galileo (1G): P7037373

Please let me know, if you need anything to resolve this issue. Thank you again for your support. Looking forward for this issue's resolution.

Regards,
Ali

**Comment by vivekjyotipramanik** [comment]
Hi Ali,

Looks like your account is expiring today. Please feel free to request for a trial credentials through Developer Network. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by imAliAsad** [comment]
HI @vivekjyotipramanik ,

Thank you very much man. You're awesome. After using new trial credentials, application is working fine. Thanks mate!

Best Wishes,
Ali Asad
