### ISSUE TITLE
TravelPort UAPI Portable Class Library

### ISSUE THREAD

**Issue by AnjumShakeelJanjua** [Travelport/travelport-uapi-tutorial-c-sharp#40]
Hi 
Me and my team are currently facing an issue in TravelPort UAPI Sample Application C#. We want to use the data from this sample in our Cross-Platform Mobile Application but we are facing issue like "we are unable to add references to the dlls such as System.ServiceModel and System.Configuration in our Portable Class Library". 
Is there any alternative way to use TravelPort UAPI in our Mobile App???

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

System.Servicemodel and syustem.configuration are .net library classes and not dependent on Travelport Universal API. Could you please confirm which .net framework version you are using.

Could you please elaborate more on where you are getting the issue, is it in the Sample c# application or in the mobile application. If it is in the mobile application, We need more information on the technology you are using in the application and more details on how you are planning to add the sample application in your app.

Please let  me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi vivek
Thanks for replying back

I am not facing any issue in the sample C# application.
The problem is that I want to make a portable class library to be used in my Cross-Platform Application but in the Portable Class Library I am receiving issues in
1) System.configuration errors in picture1
![pcl_system configuration](https://cloud.githubusercontent.com/assets/16688695/16757716/212e1bc0-4827-11e6-9a54-f0087a40fbf5.PNG)

2)And when I try to build the PCL there are errors(a lot of them) in the AirService Reference.cs in picture2
![reference cs errors](https://cloud.githubusercontent.com/assets/16688695/16757817/91591be8-4827-11e6-90a1-da287a15d44b.PNG)

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

As c# sample is working fine, looks like this is a issue with PCL. Again, without working on the complete code, it is quite impossible to check the issue. But we can try.

Please add the reference System.Configuration directly and try again. Please check the sample application/References and you will get the idea. We have done the same.  Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
I tried doing that. I added the dlls System.Configuration and System.ServiceModel from physical location as well. System.Configuration reference was added but I was still receiving errors but In case of System.ServiceModel it said that this dll has already been referenced. 

Is there an already made TravelPort UAPI for mobile available?

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

There is no Mobile sample available right now. We are planning to develop one, but it is in planning stage and we would not be able to provide any estimated release date.

To resolve you issue, Could you please remove the .net library reference and try to add only those dlls which is required. Please let me know if this resolves the issue, if not, We can schedule a webex and go through the issue. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi vivekjyotipramanik
Thanks for your reply

I already tried what you're suggesting but the .NET dll is referenced by default in the Portable Class Library and it is not allowed to change it or remove it. 
We just want "Air data" in our PCL because we are working on Airline Management System only so can you suggest any other solution to our problem?

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

System.Configuration is inside .net 4.0, could you please try changing the profile to Profile 92 or Profile 5 or Profile 328. Please let me know if the issue is still there in those profiles. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi vivekjyotipramanik,

I tried changing the PCL profiles as well but was unable to do so. I asked this in "Xamarin Forums" as well but they said that we can only change the target platforms of the application but cannot change the PCL profiles. 

Regards
Anjum Shakeel Janjua

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

I am not sure about this, as this is clearly a library related issue and not dependent on Travelport uAPI, as we can see, Travelport applications are working fine with the same libraries. 

Please provide us sometime to develop the mobile application sample and we might be able to provide more information about the issue. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi @vivekjyotipramanik
