### ISSUE TITLE
Urgent :  The HTTP request is unauthorized

### ISSUE THREAD

**Issue by dbongs** [Travelport/travelport-uapi-tutorial-c-sharp#41]
Hi Vivek,

urgent help please. i am getting the error below with my live credentials.

The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm="AXIS"'.

**Comment by vivekjyotipramanik** [comment]
Hi dbongs,

Could you please send the credentials in my email. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by dbongs** [comment]
Hi Vivek,

i have sent it

**Comment by vivekjyotipramanik** [comment]
Hi dbongs,

The credentials are working fine for me. Could you please confirm if you are using basicHttpBinding or customBinding. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by dbongs** [comment]
Hi Vivek,

i am using customBinding.

**Comment by vivekjyotipramanik** [comment]
Hi dbongs,

I have tested using your credentials and it worked fine for me. Could you please confirm if you are getting the error for any particular transaction. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by dbongs** [comment]
m getting it on LFS, do i need to specify that pcc?

**Comment by vivekjyotipramanik** [comment]
Hi dbongs,

The PCC is already tagged to your TargetBranch. Could you please check the URL which you are trying with. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by dbongs** [comment]
Hi Vivek,

here is the url: https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by vivekjyotipramanik** [comment]
Hi dbongs,

Looks like you are using preproduction URL with production credentials.
Please use the below URL. Please let me know how it goes. Thanks.

https://emea.universal-api.travelport.com/B2BGateway/connect/uAPI/

Thanks & Regards
Vivekjyoti Pramanik

**Comment by dbongs** [comment]
Hi Vivek,

Thank you so much that was the problem.
