### ISSUE TITLE
Multiple City Search 

### ISSUE THREAD

**Issue by SyedZainZaidi** [Travelport/travelport-uapi-tutorial-c-sharp#43]
Hello Dear 
Can you please help me regarding Multiple City Search I am sending the request as
`<LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v36_0" TraceId="48ec802d-9db9-4e6b-b506-e19c5e141a51" TargetBranch="P7059888" ReturnUpsellFare="true">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v36_0" OriginApplication="uAPI" />
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2016-08-26" />
  </SearchAirLeg>
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2016-08-30" />
  </SearchAirLeg>
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="KHI" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2016-09-01" />
  </SearchAirLeg>
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="KHI" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="LHR" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2016-09-03" />
  </SearchAirLeg>
  <AirSearchModifiers>
    <PreferredProviders>
      <Provider xmlns="http://www.travelport.com/schema/common_v36_0" Code="1G" />
    </PreferredProviders>
  </AirSearchModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="ADT" Age="40" DOB="1976-08-24" />
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="INF" Age="1" DOB="2015-08-24" />
  <AirPricingModifiers FaresIndicator="PublicFaresOnly">
    <AccountCodes>
      <AccountCode xmlns="http://www.travelport.com/schema/common_v36_0" Code="-" />
    </AccountCodes>
  </AirPricingModifiers>
</LowFareSearchReq>`

And in response I am getting 
`<SOAP:Fault xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <faultcode>Server.Business</faultcode>
  <faultstring>NO AVAILABILITY FOR THIS REQUEST</faultstring>
  <detail>
    <common_v36_0:ErrorInfo xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0">
      <common_v36_0:Code>3037</common_v36_0:Code>
      <common_v36_0:Service>AIRSVC</common_v36_0:Service>
      <common_v36_0:Type>Business</common_v36_0:Type>
      <common_v36_0:Description>No availability on chosen flights.</common_v36_0:Description>
      <common_v36_0:TransactionId>BAE529290A07643B706A2FB1A568CC48</common_v36_0:TransactionId>
      <common_v36_0:TraceId>48ec802d-9db9-4e6b-b506-e19c5e141a51</common_v36_0:TraceId>
    </common_v36_0:ErrorInfo>
  </detail>
</SOAP:Fault>`

Thanks in advance for your kind reply

**Comment by NirandaG** [comment]
Hi SyedZainZaidi,

I will check on this and update you.

Thank you,
Niranda

**Comment by NirandaG** [comment]
Hi SyedZainZaidi,

The reason why the Low Fare does not return the fares is there are no fares for the ISB-KHI. I have change that sector to ISB-SIN > SIN-LHR.
Please find the below working request.

  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
   <soapenv:Body>
 <LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v36_0" TraceId="48ec802d-9db9-4e6b-b506-e19c5e141a51" TargetBranch="P7059888" ReturnUpsellFare="true">
 <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v36_0" OriginApplication="uAPI" />
 <SearchAirLeg>
 <SearchOrigin>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
 </SearchOrigin>
 <SearchDestination>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
 </SearchDestination>
 <SearchDepTime PreferredTime="2016-08-26" />
 </SearchAirLeg>
 <SearchAirLeg>
 <SearchOrigin>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
 </SearchOrigin>
 <SearchDestination>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
 </SearchDestination>
 <SearchDepTime PreferredTime="2016-08-30" />
 </SearchAirLeg>
 <SearchAirLeg>
 <SearchOrigin>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
 </SearchOrigin>
 <SearchDestination>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
 </SearchDestination>
 <SearchDepTime PreferredTime="2016-09-01" />
 </SearchAirLeg>
 <SearchAirLeg>
 <SearchOrigin>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
 </SearchOrigin>
 <SearchDestination>
 <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="LHR" PreferCity="true" />
 </SearchDestination>
 <SearchDepTime PreferredTime="2016-09-03" />
 </SearchAirLeg>
 <AirSearchModifiers>
 <PreferredProviders>
 <Provider xmlns="http://www.travelport.com/schema/common_v36_0" Code="1G" />
 </PreferredProviders>
 </AirSearchModifiers>
 <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="ADT" Age="40" DOB="1976-08-24" />
 <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="INF" Age="1" DOB="2015-08-24" />
 <AirPricingModifiers FaresIndicator="PublicFaresOnly">
 <AccountCodes>
 <AccountCode xmlns="http://www.travelport.com/schema/common_v36_0" Code="-" />
 </AccountCodes>
 </AirPricingModifiers>
 </LowFareSearchReq> 
   </soapenv:Body>
</soapenv:Envelope>

Please let me know if you have any concerns on this.

Thank you,
B.Rgds,
Niranda

**Comment by NirandaG** [comment]
Hi SyedZainZaidi,

Attaching the Low Fare request.

Thank you,
Niranda

**Comment by NirandaG** [comment]
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
  <soapenv:Body>
    <LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v36_0" TraceId="48ec802d-9db9-4e6b-b506-e19c5e141a51" TargetBranch="P759888" ReturnUpsellFare="true">
      <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v36_0" OriginApplication="uAPI" />
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-08-26" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-08-30" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-09-01" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="LHR" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-09-03" />
      </SearchAirLeg>
      <AirSearchModifiers>
        <PreferredProviders>
          <Provider xmlns="http://www.travelport.com/schema/common_v36_0" Code="1G" />
        </PreferredProviders>
      </AirSearchModifiers>
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="ADT" Age="40" DOB="1976-08-24" />
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="INF" Age="1" DOB="2015-08-24" />
      <AirPricingModifiers FaresIndicator="PublicFaresOnly">
        <AccountCodes>
          <AccountCode xmlns="http://www.travelport.com/schema/common_v36_0" Code="-" />
        </AccountCodes>
      </AirPricingModifiers>
    </LowFareSearchReq>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by NirandaG** [comment]
<LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v36_0" TraceId="48ec802d-9db9-4e6b-b506-e19c5e141a51" TargetBranch="P759888" ReturnUpsellFare="true">
      <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v36_0" OriginApplication="uAPI" />
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-08-26" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="DXB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-08-30" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="ISB" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-09-01" />
      </SearchAirLeg>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="SIN" PreferCity="true" />
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v36_0" Code="LHR" PreferCity="true" />
        </SearchDestination>
        <SearchDepTime PreferredTime="2016-09-03" />
      </SearchAirLeg>
      <AirSearchModifiers>
        <PreferredProviders>
          <Provider xmlns="http://www.travelport.com/schema/common_v36_0" Code="1G" />
        </PreferredProviders>
      </AirSearchModifiers>
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="ADT" Age="40" DOB="1976-08-24" />
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v36_0" Code="INF" Age="1" DOB="2015-08-24" />
      <AirPricingModifiers FaresIndicator="PublicFaresOnly">
        <AccountCodes>
          <AccountCode xmlns="http://www.travelport.com/schema/common_v36_0" Code="-" />
        </AccountCodes>
      </AirPricingModifiers>
    </LowFareSearchReq>

**Comment by SyedZainZaidi** [comment]
Thanks alot :D
