### ISSUE TITLE
Error: No more later flights

### ISSUE THREAD

**Issue by AnjumShakeelJanjua** [Travelport/travelport-uapi-tutorial-c-sharp#48]
Hi @vivekjyotipramanik 

I am searching for availability of flights but I am receiving the following error
![errorpic](https://cloud.githubusercontent.com/assets/16688695/18660610/df75407e-7f2a-11e6-85e8-ff83ea1433e7.PNG)

I tried with my credentials on TravelPort demo site . It works there. But not in the Console Application.

And I think the error is on this line in the AirSvcTest.cs

line 37: 
rsp = client.service(request);

rsp is null. It was working yesterday but It's not working today

**Comment by vivekjyotipramanik** [comment]
Hi AnjumShakeelJanjua,

The error, "Error: No more later flights" is a valid error, which means, there is no availability for the inbound return flight. As it is preProduction environment, it is pretty common cause a huge number of developers are testing on this environment which sometimes causes lack of availability in certain markets. Could you please change the Origin/Destination and dates. Please let me know how it goes. 

Could you please confirm if you are using same origin/destination and dates in demo site which you are trying in the console application.

Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi @vivekjyotipramanik 

You were right. I tried with the same  origin and destination. It's now working as you said. I tried it in the afternoon with different values. But was having the same error over and over again. 

Thanks
