### ISSUE TITLE
AirAvailabilitySearchPortTypeClient error when adding wsdls as web reference

### ISSUE THREAD

**Issue by AnjumShakeelJanjua** [Travelport/travelport-uapi-tutorial-c-sharp#49]
Hi @vivekjyotipramanik 

I am consuming the services provided by travelport in my android application. In console application we add these services as service reference but in android there is option of web reference. But when I add these services as web reference. I get error on 

![capture](https://cloud.githubusercontent.com/assets/16688695/18703841/1674bad8-8001-11e6-888b-4453c870b805.PNG)

AirAvailabilitySearchPortTypeClient 

What can be the issue behind this???

**Comment by vivekjyotipramanik** [comment]
Hi AnjumShakeelJanjua,

From the error it looks like the code is unable to find the client class. Could you please check if the webreference generated successfully. If it was successful, it should not get the error. Also, Please browse through the generated AirService webReference to check if the AirAvailabilitySearchPortTypeClient is generated in there. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi @vivekjyotipramanik 

I looked in depth to this error and found that when I add the services as web reference the interfaces are missing in the services as shown in below figure.

![pic1issue](https://cloud.githubusercontent.com/assets/16688695/18760871/3e1e34da-811c-11e6-83b7-148c596c1e93.PNG)

When I add the services in my Console Application project or other platforms which support adding service references, the interfaces are included in those services now.

![pic2issue](https://cloud.githubusercontent.com/assets/16688695/18760908/63dee3a4-811c-11e6-913d-41e6d8088187.PNG)

I can't seem to understand why interfaces are missing in services added with web reference.
But included in services when adding with service references. 

Can you look into this?

Thanks & Regards
Anjum Shakeel Janjua

**Comment by vivekjyotipramanik** [comment]
Hi AnjumShakeelJanjua,

We have to do a little bit of research on this to provide answer to your question.
Could you please confirm if you received any errors while generating the web reference. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi @vivekjyotipramanik 

Almost all of the classes ending with PortTypeClient are missing in web references generated services

![pic1issuenew](https://cloud.githubusercontent.com/assets/16688695/18761910/472d39fa-8120-11e6-8d25-3c1920d8f224.PNG)

And I believe they are replaced by a new class as shown below

![pic2issuenew](https://cloud.githubusercontent.com/assets/16688695/18761945/64d4e7e6-8120-11e6-9b55-a79dd72456e6.PNG)

What can be the reason?
Is it because there is no App.config file in Android application?

Thanks & Regards
Anjum Shakeel Janjua

**Comment by vivekjyotipramanik** [comment]
Hi Anjum,

Could you please uncheck the "Reuse types" in specified reference assemblies and give it a try again.
Please regenerate the WebReferences after unchecking the Reuse types. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
There is no option in Android to uncheck reuse types when adding services as web reference.

![pic3issue](https://cloud.githubusercontent.com/assets/16688695/18799662/2cfe1b94-81f2-11e6-9549-b7c28c749ec7.PNG)

**Comment by IanzolaLegend** [comment]
Hello @vivekjyotipramanik, i have the same problem, i'm using wsdl V16.4.0.17.  when I add these services as web reference. I get error on.

![problema 1](https://cloud.githubusercontent.com/assets/24814685/21529070/5a8e541e-cd0d-11e6-9065-4fefae80b1db.png)

 **AirAvailabilitySearchPortTypeClient** class

I have the same error with the class: **ReferenceDataRetrievePortTypeClient**.

But, if i add the travelport wsdl as service web my problem is: 

![problema 2](https://cloud.githubusercontent.com/assets/24814685/21529062/50805508-cd0d-11e6-80d9-c90cb3ceb0e4.png)

`Thanks.
Isaias Anzola.

**Comment by vivekjyotipramanik** [comment]
Hi IanzolaLegend,

Thank you for your interest in Travelport Universal API. 
From 16.4 the service method accepts two parameters, the first one is sessionContext and the next one is the request. Please use the code as, rsp = client.service(null, request); 

If you want to use SessionContext, Please find below the link which might be helpful. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Sessions/Introduction_to_Sessioning.htm%3FTocPath%3DSessions%7C_____0

Thanks & Regards
Vivekjyoti Pramanik

**Comment by IanzolaLegend** [comment]
Thank you very much for your answer @vivekjyotipramanik , it's works.
