### ISSUE TITLE
Payment Flow unknown... how to pay IATA holder and Website Admin revenue...

### ISSUE THREAD

**Issue by UttamNCrypted** [Travelport/travelport-uapi-tutorial-c-sharp#5]
Hello VivekJyotiPramanik,

I am developing Flight booking web application in ASP.NET MVC 4 C#, SQL Server 2008 for database.

I have integrated UAPI with Galileo as provider. Work flow that I have implemented is LowFareSearchReq->AirPricing->CreateAirReservationReq.

now it's time to integrate Payment gateway and we want payment as below.

1) our website admin must have commission with each booking. It may be flat amount or percentage base amount of booking. 
Again our website admin having his personal separate account for receiving payments, he is not the person containing IATA 
code.

2) we have 2 IATA codes of different person's that we will implement(i.e. we will implement anyone of them or may be both 
IATA code on basis of mirroring concept so again have to make payment to their accounts)

3) so basically we need to do payment of two person Website Admin user Account + IATA code person's account

I have contacted Payment gateway peoples, but most of them not providing the functionality of deposite amount in multiple 
receiver account from single transaction. our client is UAE based, you can suggest as better payment gateway options for 
our project.

Please review the below questions.

1)  will we have to integrated more than one payment gateways? or we can have a single payment gateway that can deposite 
payment amount in two different account?.
2)  We want to make payment that received by Website Admin account + IATA code person’s account both are having different 
account may be having in different bank or payment gateway. So how to achieve this?
3)  FOP is compulsory to implement?
4)  here what is the role of FOP now? means we must have to set FOP for two different accounts? one for Website Admin account 
and another for IATA code person?
5)  Is FOP "card type" compulsory to provide? (i.e. Type = "VI" for Visa card)
6)  I have implemented ManualFareAdjustment at the time of FlightSearchReq, and got the updated new price in display result, 
But at the time of AirPricingReq it requires again ManualFareAdjustment. But there is no any parameter that contains Adjusted 
Amount(i.e. suppose I manually adjusted +2% amount as commission and flight base price is $100, then there is no any parameter 
that contains $2 as adjusted amount in any of the response followed by the request that we made. so how I come to know the 
amount?)
7)  can we issue air tickets from browser?

Here are the pre-production credentials:

Username: Universal API/uAPI1685394583-698e12bb 
Password: *********\* 
Target branch: P7034917 
PCC: 7NN9 

please provide answers of each and every question all are very important for us, our project development work has been 
stopped due the same reason.

so kindly review the same ASAP and get revert to me ASAP.

**Comment by vivekjyotipramanik** [comment]
Hi UttamNCrypted,

Please find below my comments regarding the questions. Thanks.

1) will we have to integrated more than one payment gateways? or we can have a single payment gateway that can deposite
payment amount in two different account?.

Could you please open an ORS ticket regarding this question.

2) We want to make payment that received by Website Admin account + IATA code person’s account both are having different
account may be having in different bank or payment gateway. So how to achieve this?

Do you mean PCC? IATA code can't be person specific. Please confirm and let me know. I am not sure what you are saying about two different IATA code. IATA code is generally based on location and each Airport and City has different IATA code.

3) FOP is compulsory to implement?

Yes, FOP is required to generate tickets.

4) here what is the role of FOP now? means we must have to set FOP for two different accounts? one for Website Admin account
and another for IATA code person?

FOP is the formOfPayment which Traveler will provide to ticket the reservation. Again, how you setup the payment gateway and to help with payment gateway we might have to setup a meeting with API support person. Please raise a ORS ticket for this one.

5) Is FOP "card type" compulsory to provide? (i.e. Type = "VI" for Visa card)

Yes, Traveler needs to provide the card type and in the XML the card type needs to be specified.

6) I have implemented ManualFareAdjustment at the time of FlightSearchReq, and got the updated new price in display result,
But at the time of AirPricingReq it requires again ManualFareAdjustment. But there is no any parameter that contains Adjusted
Amount(i.e. suppose I manually adjusted +2% amount as commission and flight base price is $100, then there is no any parameter
that contains $2 as adjusted amount in any of the response followed by the request that we made. so how I come to know the
amount?)

I am checking about this.I will let you know.

7) can we issue air tickets from browser?

The tickets can be issued anyway you want but it needs to run the AirTicketingReq to issue the ticket. So, if you want to issue the ticket using browser it is fine, but in the back end AitTicketingReq needs to be run.


Thanks & Regards
Vivekjyoti Pramanik

**Comment by UttamNCrypted** [comment]
Hello Vivekjyoti Pramanik,

Thank you for your reply. In reference of 2) question, No I didn't mean PCC, our PCC is = 7NN9. I meant by IATA code that our client provided us and that code is containing 8 digits ID, all are numeric starting from 422*******, he told us that this is the IATA code. So I got confused now.

Vivekjyoti Pramanik I really need your assistant to get the actual flow of the project, means how many things we need to collect from the client(website Owner). please suggest me the things that required to collect from client. so that I can develop project easily.

our client has provided following details up till. please suggest me the parameters that must need to fulfill to complete the project in all aspects.

please review the following details and please tell me more if there is any extra details that required to complete the project development.

Travelport UAPI pre-production credentials:

Username: Universal API/uAPI1685394583-698e12bb 
Password: ********** 
Target branch: P7034917 
PCC: 7NN9

IATA Code: 422****** (8 numeric digits code)

what other things required from client to integrated payment gateway into project?

please please provide me detailed explanation on the above. I am new to Travelport GDS flight booking development. so don't know much in the same.

It will be really greatly appreciated if you can call me on my cell +91 9558140091 ( Jignesh Jinjariya)
or we can arrange meeting/conference.

We are having weekend of on this Saturday and Sunday (12-sep, 13-sep) I will be available from Monday 14-sep.

I am available today Friday (11-sep) our working timing is (IST - 9:30 AM - 7:30 PM) = UTC +5:30

Thanking you.
Kind Regards,
Jignesh Jinjariya
Sr. Software Developer
NCrypted Technologies
http://www.ncrypted.com
 
An ISO 9001:2008 Certified Company | BID International Quality Crown (2012) Award Winner
Registered Office: 2nd floor, Shivalik 5, Gondal Road, Rajkot (Gujarat), India | +91 (281) 237 8880, 391 8880

**Comment by vivekjyotipramanik** [comment]
Hi UttamNCrypted,

I will schedule a call on Tuesday as I am completely full till Monday. Please provide your email and I will send you the meeting invitation. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by UttamNCrypted** [comment]
Hi Vivekjyoti Pramanik,

Thank you for your reply.

please find here is my Email ID jignesh.jinjariya@ncrypted.com
If there is any urgency you can call at our office NCrypted Technologies +91 (281) 237 8880, 391 8880 (contact person name = Jignesh).

We are having working hours as (IST - 9:30 AM - 7:30 PM) = UTC +5:30

Waiting for your call soon.

Best Regards,
Jignesh Jinjariya.

**Comment by UttamNCrypted** [comment]
Hi Vivekjyoti Pramanik,

Please arrange the meeting ASAP. it's very urgent for us.

if it's possible by tomorrow Wednesday (IST - 9:30 AM - 7:30 PM) = UTC +5:30

my Email: jignesh.jinjariya@ncrypted.com
Skype: jigneshjinjariya.ncrypted
Cell: +91 9558140091

please assist me ASAP.

Regards,
Jignesh Jinjariya
Sr. Software Developer
NCrypted Technologies
http://www.ncrypted.com
 
An ISO 9001:2008 Certified Company | BID International Quality Crown (2012) Award Winner
Registered Office: 2nd floor, Shivalik 5, Gondal Road, Rajkot (Gujarat), India | +91 (281) 237 8880, 391 8880
