### ISSUE TITLE
Wsdl Files

### ISSUE THREAD

**Issue by SyedZainZaidi** [Travelport/travelport-uapi-tutorial-c-sharp#50]
Hello Every One, 

Where can i get latest version wsdl files?? please help

Thanks!

**Comment by NirandaG** [comment]
Hi,

Please download the latest wsld files from the below link.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Release_Notes/What_s_New.htm%3FTocPath%3D_____3
"Release 16.3 schema"
Thank you,
B.Rgds,
Niranda

**Comment by NirandaG** [comment]
Please have a look on the below link as well for the latest schemas.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Universal_API_Schemas_and_WSDLs.htm%3FTocPath%3D_____16

Thank you,
Niranda

**Comment by SyedZainZaidi** [comment]
Thanks for the reply

**Comment by SyedZainZaidi** [comment]
The link you provided contains schema (*.xsd) files. I want Wsdl (*.wsdl) files. Please Help Thanks

**Comment by NirandaG** [comment]
The second link has a zip file where you can download all the latest schemas. Once you unzip them you will get the schemas and the wsdl files accordingly.

Thank you,
Niranda

**Comment by SyedZainZaidi** [comment]
Thanks :D
