### ISSUE TITLE
"ExceptionMessage": "UNABLE TO FARE QUOTE", when Searching Flights

### ISSUE THREAD

**Issue by socialimpulse** [Travelport/travelport-uapi-tutorial-c-sharp#51]
Hello,

Do you any problem with the testing environment? 

Sometimes we are getting a "UNABLE TO FARE QUOTE" error message when trying to search flights.

Please advice.

**Comment by vivekjyotipramanik** [comment]
Hi socialimpulse,

It is a valid error message when the fare is not available in the system. As it is PreProduction system, it may occur more frequently as so many developers/QA is testing on the same environment. Please try with different Airline/Market and atleast 2-4 months dates in future. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
