### ISSUE TITLE
"000279 VERIFY DATE SEQUENCE IN ITINERARY "

### ISSUE THREAD

**Issue by socialimpulse** [Travelport/travelport-uapi-tutorial-c-sharp#52]
Hello,

I am trying to price a connecting flight but I am always getting the following error message:

"000279 VERIFY DATE SEQUENCE IN ITINERARY "

Please find enclosed the request.

Thank you so much for your help.

[price.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/502180/price.txt)

**Comment by vivekjyotipramanik** [comment]
Hi  socialimpulse,

You are using same destination for both of the segment. Could you please try with different segments.
Also, Could you please change the OriginApplication to UAPI. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by socialimpulse** [comment]
Hello, same issue. Please check the new request. 

Thanks for your help.
[PricingError.txt](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/files/506988/PricingError.txt)

**Comment by vivekjyotipramanik** [comment]
Hi socialimpulse,

Looks like, The first AirSegment arrival time is too close or after the 2nd AirSegment departure time. In the request I can't see the 1st AirSegment Arrival time. Could you please provide me the request with all the Arrival and Departure times. The error is a valid error and might come in the scenario where one of the AirSegment is too close to other. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by socialimpulse** [comment]
Thanks for your response, I am not sending the arrival times, Do I have to? We are designing a API and we want to send as minimum data as possible.

Please advice.

**Comment by vivekjyotipramanik** [comment]
Hi socialimpulse,

I am saying, If then Arrival time of one segment is close to to after the departure time of next segment then you will get this error. But in this case, I could not analyze that cause you are not sending the Arrival time. I am saying, without seeing the complete request, it is tough to analyze. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by socialimpulse** [comment]
I check the arrival times and they are not close, however I am preparing a complete request so you can help me analyzing.

Thank you so much.

**Comment by socialimpulse** [comment]
I started sending the arrival times in the request and its working now, so it seems that arrival times and dates are mandatory.

Thanks for your help ;)
