### ISSUE TITLE
getting 00002 INVALID INPUT when making AirPriceReq

### ISSUE THREAD

**Issue by gakshat14** [Travelport/travelport-uapi-tutorial-c-sharp#55]
This is the request I'm making for AirPriceReq looks like this
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
  <soapenv:Body>
    <air:AirPriceReq xmlns:air="http://www.travelport.com/schema/air_v34_0" xmlns:com="http://www.travelport.com/schema/common_v34_0" xmlns:common_v34_0="http://www.travelport.com/schema/common_v34_0" AuthorizedBy="user" CheckFlightDetails="true" TargetBranch="P7004166" TraceId="trace">
      <common_v34_0:BillingPointOfSaleInfo OriginApplication="UAPI" />
      <air:AirItinerary>
        <air:AirSegment ArrivalTime="2016-10-13T08:35:00.000+02:00" AvailabilityDisplayType="Fare Shop/Optimal Shop" AvailabilitySource="S" Carrier="LH" ChangeOfPlane="false" ClassOfService="T" DepartureTime="2016-10-13T06:35:00.000+02:00" Destination="BCN" Distance="681" ETicketability="Yes" Equipment="E95" FlightNumber="1808" FlightTime="120" Group="0" Key="Kr5DQHo/QXCFof4jIj2WoA==" LinkAvailability="true" OptionalServicesIndicator="false" Origin="MUC" ParticipantLevel="Secure Sell" PolledAvailabilityOption="Polled avail used" ProviderCode="1G" />
        <air:AirSegment ArrivalTime="2016-10-20T09:50:00.000+02:00" AvailabilityDisplayType="Fare Shop/Optimal Shop" AvailabilitySource="S" Carrier="LH" ChangeOfPlane="false" ClassOfService="T" DepartureTime="2016-10-20T07:50:00.000+02:00" Destination="MUC" Distance="681" ETicketability="Yes" Equipment="321" FlightNumber="1817" FlightTime="120" Group="1" Key="ALQbAY14RSWxt9gl7VzeNw==" LinkAvailability="true" OptionalServicesIndicator="false" Origin="BCN" ParticipantLevel="Secure Sell" PolledAvailabilityOption="Polled avail used" ProviderCode="1G" />
      </air:AirItinerary>
      <air:AirPricingModifiers PlatingCarrier="LH"></air:AirPricingModifiers>
      <common_v34_0:SearchPassenger BookingTravelerRef="gr8AVWGCR064r57Jt0+8bA==" Code="ADT" />
      <air:AirPricingCommand />
    </air:AirPriceReq>
  </soapenv:Body>
</soapenv:Envelope>`
I have been stuck at it for weeks any help would be appreciated.

**Comment by vivekjyotipramanik** [comment]
Hi gakshat14,

Thank you for your interest in Travelport Universal API. The issue might be because of your account setup.
I would recommend to request for a new set of credentials. 

Also, Please send me the username which you are using. In the meantime you can request the new credentials and use that. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by gakshat14** [comment]
Universal API User ID:  Universal API/uAPI1750790704-327b5ca9
Universal API Password:  Gmk7ghAgXTzRmx7Qq3BFb6HEw
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7004166
URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by NirandaG** [comment]
Hi gakshat14,
The AirPrice request works fine. I believe your credentials would cause this.
Could you please request new credentials and give a try?
Thank you,
Niranda
