### ISSUE TITLE
Null Reference Exception in booking Code

### ISSUE THREAD

**Issue by AnjumShakeelJanjua** [Travelport/travelport-uapi-tutorial-c-sharp#58]
Hi @vivekjyotipramanik 

Hope you are well. I am having null reference exception in bookingWithLowFare 

        public static string BookWithLowFare(AirPriceRsp priceRsp, AirPricingSolution lowestPrice)
        {
            string bookingCode = null;

            //Check Pricing with AirSegments = flight with price
            if (lowestPrice != null && priceRsp.AirItinerary != null)
            {
                AirBookTest book = new AirBookTest();

                AirCreateReservationRsp bookResponse = new AirCreateReservationRsp();

                book.AirBook(lowestPrice, priceRsp.AirItinerary);

                if (bookResponse != null)
                {
                   //Null Reference Exception here
                    bookingCode = bookResponse.UniversalRecord.LocatorCode;

                    UniversalRetrieveTest univ = new UniversalRetrieveTest();

                    univ.RetrieveRecord(bookingCode);
                }
            }
            return bookingCode;
        }

I am having response in priceRsp and lowestPrice but bookResponse.UniversalRecord.LocatorCode throws a nullReferenceException. What can be the problem?

**Comment by NirandaG** [comment]
Hi AnjumShakeelJanjua,

Are you getting a successful bookResponse? Could you please send me the returned response of bookResponse?
Also please attach the priceRsp and lowestPrice results.

Thank you,
B.Rgds,
Niranda

**Comment by AnjumShakeelJanjua** [comment]
Hi @NirandaG 
Thank you for your prompt reply. I am not getting anything in the bookResponse either . What can be the problem?

**Comment by AnjumShakeelJanjua** [comment]
I am getting the problem probably on this line. 

![airbook exception](https://cloud.githubusercontent.com/assets/16688695/19650937/6bf36c4c-9a24-11e6-928d-9f0408c4ee8c.PNG)

This line throws this exception.

Message = "Message From Galileo : Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: Exception ReturnedERR: AGENT ID - GALILEOWith the Dynamic GTID list of:A806E4 "

**Comment by vivekjyotipramanik** [comment]
Hi AnjumShakeelJanjua,

The reason you are getting the error cause the Agent If of your TargetBranch fell of the preproduction system. Could you please provide your username and targetBranch so that we can restore the same. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi vivekjyotipramanik

Thank you for you quick reply. 
Here are my credentials:

Username: Universal API/uAPI-601628191
Password: JbNxN3bTYypfE8EFwqBcrwWaH
TargetBranch: P105205

**Comment by vivekjyotipramanik** [comment]
Hi AnjumShakeelJanjua,

We have rebuilt the sign on. Could you please try again. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by AnjumShakeelJanjua** [comment]
Hi @vivekjyotipramanik 

Thanks a lot. The issue has been resolved and I am now able to successfully generate the booking code.

Regards,
Anjum ShakeelJanjua
