### ISSUE TITLE
Galileo 30 days trail credentials

### ISSUE THREAD

**Issue by Chandrasekarwaran** [Travelport/travelport-uapi-tutorial-c-sharp#71]
Hi,
   This is chandrasekar.I'm Developing travel application by using galileo 30 days trail api.But this credentials are not working.i got a error like ---- the http request is unauthorized with client authentication scheme 'basic' .the authentication header received from the server was 'Basic realm='\"AXIS\"''.

Universal API User ID:  Universal API/uAPI8422215514
 
 
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P105400
 
Kindly revert as soon as possible.

**Comment by vivekjyotipramanik** [comment]
Hi  Chandrasekarwaran,

Looks like your account is locked. We are working on this and will provide an update soon. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Chandrasekarwaran,

We have unlocked the account. Could you please try again. Please let us know how it goes. Thanks.

**Comment by Mohammedmehraj** [comment]
Hi i too have the same issue-
the http request is unauthorized with client authentication scheme 'basic' .the authentication header received from the server was 'Basic realm='"AXIS"''.

Universal API User ID:  Universal API/uAPI8024288652-6e0affbe

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7009947

i'm using visual studio 2015 please support me on the above issue
