### ISSUE TITLE
The HTTP request is unauthorized  exception in Galileo 30 days trail

### ISSUE THREAD

**Issue by Mohammedmehraj** [Travelport/travelport-uapi-tutorial-c-sharp#72]
Hello guys when i try to connect from my console app to travelport api  i am getting the following exception
**The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm=\"AXIS\"'.**

Your Credentials: Universal API Web Services
Universal API User ID:  Universal API/uAPI8024288652-6e0affbe

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7009947

i am using visual studio 2015 please suggest its very urgent

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Could you please try in http://demo.travelportuniversalapi.com/ with your credentials and let us know if you are getting the same error over there. I will check from our side if the credentials are locked. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

We have unlocked the account. Could you please try again. Thanks.

**Comment by Mohammedmehraj** [comment]
It works thank you

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Glad to hear this. We are closing this issue. Please feel free to open another issue in case of any questions. Thanks.
