### ISSUE TITLE
WCF Error:The provided URI scheme 'https' is invalid; expected 'http'.\r\nParameter name: via

### ISSUE THREAD

**Issue by Mohammedmehraj** [Travelport/travelport-uapi-tutorial-c-sharp#73]
I am trying to connect travelport uapi from my WCF application i have created a AirportDetailsService.svc which returns a json object of AllAirports i have added service reference of AirService, SystemService, Utility 
below is webconfig service section when i try to debug i am getting a error The provided URI scheme 'https' is invalid; expected 'http'.\r\nParameter name: via
Note: i have created my webconfig similar to appconfig of sample consoleapplication travelportUAPI

```
 <services>
<service name="TravelportUAPI.Services.AirportDetailsService" behaviorConfiguration ="ServiceBehaviour">
          <endpoint address="" binding ="webHttpBinding" behaviorConfiguration ="webBehavior" contract="TravelportUAPI.Services.IAirportDetailsService">
            </endpoint>
        </service>
    </services>
```

**Comment by Mohammedmehraj** [comment]
Below is my endpoint config:`
<service name="TravelportUAPI.Services.AirportDetailsService" behaviorConfiguration="metadataBehavior">
        <endpoint 
          address="" 
          binding="basicHttpBinding"
          contract="TravelportUAPI.Services.IAirportDetailsService"/>
        <endpoint 
          address="mex" 
          binding="mexHttpBinding" 
          contract="IMetadataExchange"/>
     </service>`

Below is the binding configuration for "SystemPingPort" please suggest what do i pass in security mode to avoid the error The provided URI scheme 'https' is invalid; expected 'http'.\r\nParameter name: via

 <binding name="SystemPingBinding" >
          <security mode="Transport"> 
            <transport clientCredentialType="None" proxyCredentialType="None" realm=""/> 
            <message clientCredentialType="Certificate" algorithmSuite="Default" />
          </security> 
        </binding>

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

I believe you are using basicHttpBinding and that is causing the issue here. Could you please try with customBinding and CustomServiceBinding. Please find below the link to the app.config with customBinding. 
Please let us know how it goes. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/blob/master/ConsoleApplication1/ConsoleApplication1/App.config

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

Could you please confirm if we can close this issue. Thanks.

**Comment by Mohammedmehraj** [comment]
it works thank yu
