### ISSUE TITLE
Unable to fare quote in Lowfaresearch

### ISSUE THREAD

**Issue by Mohammedmehraj** [Travelport/travelport-uapi-tutorial-c-sharp#74]
Hi i am trying to do a lowfaresearch in consoleapplication1 my origin "DEN" ,destination = "SFO" i am getting a exception Unable to fare quote please suggest

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

Could you please confirm if you are facing the same issue. If you are testing in PreProduction environment , this error might come cause of limited test data. Please try with SYD to MEL or JFK to LHR and let us know if you are facing the same issue. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Could you please confirm if we can close this issue. Thanks.

**Comment by Mohammedmehraj** [comment]
Yes working with SYD to MEL you can close the issue
