### ISSUE TITLE
Exception while booking a ticket in galileo 30 days trail

### ISSUE THREAD

**Issue by Mohammedmehraj** [Travelport/travelport-uapi-tutorial-c-sharp#75]
Hi,
i am not able to book a ticket i am getting a following exception in AirBookTest and my other doubt is in consoleappication1 you are passing the entire classes its very tuff to understand what is mandatory data 

Message From Galileo : Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: Exception ReturnedERR: AGENT ID - GALILEOWith the Dynamic GTID list of:A80881

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

Could you please provide the username and targetBranch you are using. Thanks.

**Comment by Mohammedmehraj** [comment]
Username:Universal API/uAPI8024288652-6e0affbe
Branch:1GTargetBranch

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

The TargetBranch you have provided is incorrect. Could you please provide the Username/TargetBranch which you have received from travelport with the trial credentials in the email. In code, you have to add that targetBranch and user and password in app.config. Thanks.

**Comment by Mohammedmehraj** [comment]
<add key="1GTargetBranch" value="P7009947" />
Already added in appconifig

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Could you please provide the Username and TargetBranch which you have provided in app.config. Thanks.

**Comment by Mohammedmehraj** [comment]
'<add key="Username" value="Universal API/uAPI8024288652-6e0affbe" />'
'<add key="1GTargetBranch" value="P7009947" />'

I am doing lowfaresearch in that i am i need to parse the lowFareSearchRsp who do i parse it?? to json or xml plz suggest struck with this from hours

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

UAPI uses SOAP XML for communication and for all of its services. Please find below the link with all the details. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm

**Comment by Mohammedmehraj** [comment]
Still getting the same exception in consoleappication1 AirBookTest in the below line plz suggest its urgent

`  reservationRsp = client.service(null, reservationReq);`

```
 <add key="Username" value="Universal API/uAPI8024288652-6e0affbe" />
    <add key="1GTargetBranch" value="P7009947" />
```

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Could you please request for a new set of trial credentials and give it a try. Thanks.

**Comment by Mohammedmehraj** [comment]
Tried with new credendentials same exception i am getting 
origin="SYD", Destination="MEL"

` <add key="Username" value="Universal API/uAPI1344578770-c7803131" />
    <add key="1GTargetBranch" value="P7039109" />`

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

We are working on this and will provide an update as soon as it is resolved. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Mohammedmehraj,

Could you please try again. Please let us know how it goes. Thanks.

**Comment by Mohammedmehraj** [comment]
Thank you it works

**Comment by vivekjyotipramanik** [comment]
Hi  Mohammedmehraj,

Glad to hear this. We are closing this issue. Please feel free to open another issue in case of any questions. Thanks.
