### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm=\"AXIS\"'." -> The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by AlbertoP64** [Travelport/travelport-uapi-tutorial-c-sharp#91]
Hi, my account must be locked, also got the Inner exception I've appended in title.
My credential follows, please someone could unlock my account ASAP.
I link @vivekjyotipramanik as abitually replying this kind of issues.
Thanks and regards
```
Universal API User ID:                    Universal API/uAPI2726420276-3b2e1c43
Universal API Password:                   XyBCAkeFZt7ccKzdkBqnmZ5Qz
Branch Code (TargetBranch) for ProviderName (ProviderCode):
  Branch Code for Galileo (1G):           P7037567
```

**Comment by vivekjyotipramanik** [comment]
Hi  AlbertoP64,

We are working on to unlock this. We will notify you as soon as it is unlocked. Thanks.

**Comment by AlbertoP64** [comment]
Hi Mr. @vivekjyotipramanik , 

we are worried about our request.
The credentials above were a thirty days demo/test, emitted on 29/7/2017 directly to our customer.
We don't know the correct policies, but can these credentials be renewed?

Our customer have requested the pre-production credentials, but  that request is blocked for other reasons (vacations, logistics, bureaucracy...). We'll hopefully get to see some progress next weeks.

We have some deadlines to attend to, and we need the credentials as soon as possible to continue our work.
Can you please reactivate our credentials to cover this time period?
If that's not possible, what you advice us to do?

Waiting for you answer.
Regards

**Comment by vivekjyotipramanik** [comment]
Hi AlbertoP64,

Trial crednetials can't be renewed as the same account gets reallocated to other users as soon as it  free up. Please request for a different set of trial credentials.

if you need PreProduction credentials, Please contact your Travelport account manager and he/she will be able to help you with PreProduction credentials. The PreProduction credentials does not expire.

Please let us know how it goes. Thanks.

**Comment by AlbertoP64** [comment]
Thanks mr. @vivekjyotipramanik for the prompt reply.

We're sorry we were misunderstanding completely. To our defense, seeking for error message - not very talking though - , we found many issues replied like that [issue 89](https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/issues/89) and deducted wrong.

We do talk with our customer asking him to speed up the setup of new credentials, and if it's time wasting, we do seek for a new trial.
Thanks and regards

**Comment by vivekjyotipramanik** [comment]
Hi  AlbertoP64,

I am unable to understand the question, if your credential is locked, we can unlock it. But if it is expired, you have to ask for a new trial credentials. I am not sure what you meant by "deducted wrong". Could you please clarify. Thanks.

**Comment by AlbertoP64** [comment]
Yes Mr. Vivek I try to explain better. 
We got the (thread title) error message while using the trial credentials on our trial development.
As we sought the error on the web, we found TravelPort GitHub issues, that were mostly solved by 'unlocking' the relative accounts.
At this point, we mistakenly concluded that also our case will fit same treatment  😄 .
Instead now we know that we were in a totally different condition, so we beg our pardon.
Thanks Mr. Vivek, and please consider that issue closed.
