### ISSUE TITLE
Travelport UAPI integration

### ISSUE THREAD

**Issue by dfmstevens** [Travelport/travelport-uapi-tutorial-c-sharp#92]
Hi vivekjyotipramanik,

I'm looking for support with the integration of the Travelport integration on our webplatform. Can you help us with this? You can reach me on dfm.stevens@gmail.com.

Hoping to hear from you. Thank you.

Have a nice day.

Regards Dan

**Comment by vivekjyotipramanik** [comment]
Hi dfmstevens,

For support regarding UAPI, Please open a ORS or MyTravelport Ticket or contact your Travelport account manager. Through github we support general questions and coding related issues. Please feel free to open a issue regarding your question and we will answer them as soon as possible. Thanks.

**Comment by dfmstevens** [comment]
Thanks, for your reply. We work already with travelport and have an account
manager, but we lack the experience on how to handle errors etc, so we're
looking for an developer who can support us. Do you have any suggestions?

Thanks.

On Aug 31, 2017 8:10 PM, "vivekjyotipramanik" <notifications@github.com>
wrote:

Hi dfmstevens,

For support regarding UAPI, Please open a ORS or MyTravelport Ticket or
contact your Travelport account manager. Through github we support general
questions and coding related issues. Please feel free to open a issue
regarding your question and we will answer them as soon as possible. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/issues/92#issuecomment-326345641>,
or mute the thread

**Comment by vivekjyotipramanik** [comment]
Hi  dfmstevens,

In that case, Please open an ORS ticket and give me the number. I will pick it up and schedule a meeting to discuss through the ORS ticket. Thanks.

**Comment by dfmstevens** [comment]
Hi,

Sorry, this is new to me. What is ORS?

Regards dan

On Aug 31, 2017 8:51 PM, "vivekjyotipramanik" <notifications@github.com>
wrote:

Hi dfmstevens,

In that case, Please open an ORS ticket and give me the number. I will pick
it up and schedule a meeting to discuss through the ORS ticket. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/issues/92#issuecomment-326356471>,
or mute the thread

**Comment by vivekjyotipramanik** [comment]
Hi dfmstevens,

It is the online reporting system. If you do not have access to it or you have access in MyTravelport, Please feel free to raise a ticket in there as well. If you do not have access in any of them, Please contact your account manager and he/she will assist you with it. Please find below the link for both of them. 

May I know, what you currently use to raise tickets with Travelport. Thanks.


ORS : https://support.travelport.com/tdssupport/ors_view_requests.asp

MyTravelport : https://my.travelport.com

**Comment by dfmstevens** [comment]
Hi, 

We use: https://support.travelport.com/tdssupport/main.asp

If i put a ticket (PT) in there, how can i reach you?

Regards Dan

**Comment by vivekjyotipramanik** [comment]
Hi dfmstevens,

The https://support.travelport.com/tdssupport/main.asp is actually ORS. Please give me the PT number once you open it and I will pick up from ORS. Thanks.

**Comment by dfmstevens** [comment]
We use PT(244863) 1G - CCC process

Is this good enough for you? Can we have a chat tomorrow?

**Comment by vivekjyotipramanik** [comment]
Hi dfmstevens,

The 244863 is for CCC process and already assigned to a support analyst. Could you please open a new PT for UAPI as Product and I will pick it up. I would not be able to pick up a PT which is already assigned and being worked on. Thanks.

**Comment by dfmstevens** [comment]
Hi,

I've created PT251798  - Globist - TravelPort integration .

Looking forward speaking to you.

Regards Dan


Regards,

Dan Stevens
+971 5 26236848

**Comment by vivekjyotipramanik** [comment]
Hi dfmstevens,

Thanks for opening the ticket. I have assigned it to myself. Let us discuss over ORS. I am closing this issue and I have updated the ORS with my comments. Thanks.
