### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm=\"AXIS\

### ISSUE THREAD

**Issue by tnking83** [Travelport/travelport-uapi-tutorial-c-sharp#96]
Please assist.  After looking around it seems like my account may be locked.   #89

```
<add key="Username" value="Universal API/uAPI4829319059-102994be" />
    <add key="1PTargetBranch" value="P108154" />
```

**Comment by vivekjyotipramanik** [comment]
Hi tnking83,

Could you please confirm if you have tried your credentials in demosite and if it is working there. 
If you are using basicHttpBinding, Please change it to customBinding. Please find below the app.config with customBinding. Please let us know how it goes. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/blob/master/ConsoleApplication3/ConsoleApplication3/App.config

**Comment by tnking83** [comment]
My credentials in the demo site work correctly.  I am attempting to send a ping request in the sample project which uses custom binding in the sample appconfig shown at the link below.  The only changes I made to the project were adding my username, password, target branch, and url prefix.


https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/blob/master/ConsoleApplication1/ConsoleApplication1/App.config

I have found that the httpHeader helper is adding a basic authorization.  Could this be the issue?

**Comment by vivekjyotipramanik** [comment]
Hi tnking83,

In UAPI we have to use basic authorization. The targetBranch, username and password needs to be added in the app.config of the project, there is already placeholder for them. Could you please add the credentials in the app.config and give it a try again. Please let us know how it goes. Thanks.

**Comment by tnking83** [comment]
I was able connect after deleting and re-cloning the the repo.  I had to remove the the 1G branch key from the app.config.  Thanks.
